import { contextBridge, ipcRenderer } from 'electron';

// Ranh giới an ninh duy nhất giữa renderer và main: chỉ lộ ra các operation
// nghiệp vụ đặt tên rõ ràng — renderer KHÔNG có cách nào gửi SQL tự do.
contextBridge.exposeInMainWorld('qcApi', {
  hasAnyUsers: () => ipcRenderer.invoke('auth:hasAnyUsers'),
  currentUser: () => ipcRenderer.invoke('auth:currentUser'),
  bootstrapAdmin: (input: unknown) => ipcRenderer.invoke('auth:bootstrapAdmin', input),
  login: (input: unknown) => ipcRenderer.invoke('auth:login', input),
  logout: () => ipcRenderer.invoke('auth:logout'),
  listUsers: () => ipcRenderer.invoke('auth:listUsers'),
  createUser: (input: unknown) => ipcRenderer.invoke('auth:createUser', input),
  updateUser: (input: unknown) => ipcRenderer.invoke('auth:updateUser', input),
  resetUserPassword: (input: unknown) => ipcRenderer.invoke('auth:resetPassword', input),
  changeOwnPassword: (input: unknown) => ipcRenderer.invoke('auth:changeOwnPassword', input),
  listInstruments: () => ipcRenderer.invoke('config:listInstruments'),
  saveInstrument: (input: unknown) => ipcRenderer.invoke('config:saveInstrument', input),
  listTests: () => ipcRenderer.invoke('config:listTests'),
  saveTest: (input: unknown) => ipcRenderer.invoke('config:saveTest', input),
  listTestLevels: (testId: string) => ipcRenderer.invoke('config:listTestLevels', testId),
  saveTestLevel: (input: unknown) => ipcRenderer.invoke('config:saveTestLevel', input),
  listActivity: (limit?: number) => ipcRenderer.invoke('config:listActivity', limit),
  queryActivity: (input: unknown) => ipcRenderer.invoke('audit:query', input),
  queryPoints: (testId: string, level: number) => ipcRenderer.invoke('entry:queryPoints', testId, level),
  addPoint: (input: unknown) => ipcRenderer.invoke('entry:addPoint', input),
  voidPoint: (input: unknown) => ipcRenderer.invoke('entry:voidPoint', input),
  listTestSummaries: () => ipcRenderer.invoke('westgard:listTestSummaries'),
  analyzeLevel: (testId: string, level: number) => ipcRenderer.invoke('westgard:analyzeLevel', testId, level),
  saveRuleAction: (testId: string, ruleId: string, on: boolean) => ipcRenderer.invoke('westgard:saveRuleAction', testId, ruleId, on),
  listSigmaPeriods: (testId: string) => ipcRenderer.invoke('sigma:listPeriods', testId),
  saveSigmaPeriod: (input: unknown) => ipcRenderer.invoke('sigma:savePeriod', input),
  listNceRecords: () => ipcRenderer.invoke('nce:listRecords'),
  createNce: (input: unknown) => ipcRenderer.invoke('nce:create', input),
  approveNce: (input: unknown) => ipcRenderer.invoke('nce:approve', input),
  returnNce: (input: unknown) => ipcRenderer.invoke('nce:returnForRevision', input),
  cancelNce: (input: unknown) => ipcRenderer.invoke('nce:cancel', input),
  setNceCompletedDate: (input: unknown) => ipcRenderer.invoke('nce:setActionCompletedDate', input),
  markNceEffectiveness: (input: unknown) => ipcRenderer.invoke('nce:markEffectiveness', input),
  listReagentComparisons: () => ipcRenderer.invoke('reagent:listComparisons'),
  createReagentComparison: (input: unknown) => ipcRenderer.invoke('reagent:createComparison', input),
  saveReagentMetadata: (input: unknown) => ipcRenderer.invoke('reagent:saveMetadata', input),
  saveReagentRows: (input: unknown) => ipcRenderer.invoke('reagent:saveRows', input),
  removeReagentComparison: (input: unknown) => ipcRenderer.invoke('reagent:removeComparison', input),
});
