export function createRouterShellController(deps:{find:(id:string)=>any;findShell:()=>any;lab:()=>any;pages:()=>[string,string][];canAccess:(id:string,user:any)=>boolean;escape:(value:any)=>string;escapeAttr:(value:any)=>string;app:()=>any;license:()=>any;storage:{setItem:(key:string,value:string)=>void}}){
  const brandTitle=()=>deps.lab().brandTitle||'QC Lab',brandSub=()=>deps.lab().brandSub||'Nội kiểm xét nghiệm',brandMarkText=()=>String(deps.lab().logoText||'QC').slice(0,4),brandLogo=()=>deps.lab().logoData||'';
  const renderBrand=()=>{const element=deps.find('brandBox');if(!element)return;const logo=brandLogo();element.innerHTML=`<div class="brand-mark">${logo?`<img src="${deps.escapeAttr(logo)}" alt="">`:deps.escape(brandMarkText())}</div><div>${deps.escape(brandTitle())}<small>${deps.escape(brandSub())}</small></div>`;};
  const nav=({page,user,icon}:{page:string;user:any;icon:(id:string)=>string})=>{const element=deps.find('nav');if(!element)return;const scrollTop=element.scrollTop,groups:[string,string[]][]=[['Theo dõi',['dash','entry','westgard','sigma']],['Vận hành',['reagent','actions','report']],['Quản trị',['manage','users','audit','settings']]];element.innerHTML=groups.map(([label,ids])=>{const items=deps.pages().filter(([id])=>ids.includes(id)&&deps.canAccess(id,user));return items.length?`<div class="nav-group">${label}</div>`+items.map(([id,title])=>`<button class="${id===page?'active':''}" aria-current="${id===page?'page':'false'}" data-action="go" data-args='${JSON.stringify([id])}'><span class="ic" aria-hidden="true">${icon(id)}</span>${title}</button>`).join(''):'';}).join('');element.scrollTop=scrollTop;};
  const licensedLabName=()=>{const license=deps.license();return license&&license.lab?String(license.lab):'';},trialInfo=()=>{const trial=deps.license()?.trial;return trial&&trial.active?trial:null;};
  const sideFoot=()=>{const element=deps.find('sideFoot');if(!element)return;const app=deps.app()||{version:'dev'},lab=licensedLabName(),licensed=lab?`<div class="hint" style="color:#8ea3b2">Cấp phép: <b style="color:#c3d3dd">${deps.escape(lab)}</b></div>`:'',trial=trialInfo(),trialLine=trial?`<div class="hint" style="color:${trial.daysLeft<=7?'#e2a33d':'#8ea3b2'}">Dùng thử: còn <b style="color:${trial.daysLeft<=7?'#e2a33d':'#c3d3dd'}">${trial.daysLeft} ngày</b></div>`:'';element.innerHTML=`<div class="foot-panel"><div class="hint">Ver: ${deps.escape(app.version||'dev')}</div>${licensed}${trialLine}</div>`;};
  const toggleSidebarNav=()=>{const shell=deps.findShell();if(!shell)return;const collapsed=shell.classList.toggle('nav-collapsed');try{deps.storage.setItem('qclab_nav_collapsed',collapsed?'1':'0');}catch{}};
  return{brandTitle,brandSub,brandMarkText,brandLogo,renderBrand,nav,licensedLabName,trialInfo,sideFoot,toggleSidebarNav};
}
