export function reportXlsxStyles(){
  const fonts=['<font><sz val="9"/><name val="Arial"/><color rgb="FF16202B"/></font>','<font><b/><sz val="9"/><name val="Arial"/><color rgb="FF16202B"/></font>','<font><b/><sz val="12"/><name val="Arial"/><color rgb="FFFFFFFF"/></font>','<font><b/><sz val="15"/><name val="Arial"/><color rgb="FF16202B"/></font>','<font><sz val="9"/><name val="Arial"/><color rgb="FF647686"/></font>','<font><b/><sz val="9"/><name val="Arial"/><color rgb="FF244452"/></font>','<font><i/><sz val="9"/><name val="Arial"/><color rgb="FF647686"/></font>'];
  const fills=['<fill><patternFill patternType="none"/></fill>','<fill><patternFill patternType="gray125"/></fill>'];
  ['0E8F8F','E7F1F4','FFFFFF','FDECEA','FFF6E5'].forEach(color=>fills.push('<fill><patternFill patternType="solid"><fgColor rgb="FF'+color+'"/></patternFill></fill>'));
  const borders=['<border><left/><right/><top/><bottom/><diagonal/></border>','<border><left style="thin"><color rgb="FFCBD8DF"/></left><right style="thin"><color rgb="FFCBD8DF"/></right><top style="thin"><color rgb="FFCBD8DF"/></top><bottom style="thin"><color rgb="FFCBD8DF"/></bottom><diagonal/></border>'];
  const xf=(font:number,fill:number,border:number,horizontal:string,vertical:string,wrap:number)=>'<xf numFmtId="0" fontId="'+font+'" fillId="'+fill+'" borderId="'+border+'" xfId="0" applyFont="1" applyFill="1" applyBorder="1" applyAlignment="1"><alignment'+(horizontal?' horizontal="'+horizontal+'"':'')+(vertical?' vertical="'+vertical+'"':'')+(wrap?' wrapText="1"':'')+'/></xf>';
  const xfs=['<xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/>',xf(3,0,0,'center','center',0),xf(4,0,0,'center','center',1),xf(2,2,0,'left','center',0),xf(5,3,1,'left','center',1),xf(0,4,1,'left','center',1),xf(5,3,1,'center','center',1),xf(0,4,1,'center','center',1),xf(0,4,1,'left','center',1),xf(6,0,0,'left','center',1),xf(1,5,1,'center','center',1),xf(1,6,1,'center','center',1)];
  return '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="'+fonts.length+'">'+fonts.join('')+'</fonts><fills count="'+fills.length+'">'+fills.join('')+'</fills><borders count="'+borders.length+'">'+borders.join('')+'</borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="'+xfs.length+'">'+xfs.join('')+'</cellXfs><cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles></styleSheet>';
}
