'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','nce','action-rule-options.ts')).href;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--eval',`import {actionRuleOptions} from ${JSON.stringify(source)}; console.log(JSON.stringify(actionRuleOptions(['1-3s','2-2s'])));`],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'không thể chạy luật NCE TypeScript');
assert.deepEqual(JSON.parse(result.stdout),[['','Không có luật Westgard'],['1-3s','1-3s'],['2-2s','2-2s']]);
console.log('Action rule options TypeScript tests passed');
