'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','nce','action-form-closed-html.ts')).href;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--eval',`import {actionFormClosedHtml} from ${JSON.stringify(source)}; console.log(actionFormClosedHtml({title:'Chọn sự cố',message:'Mở hồ sơ',actionHtml:'<button>Lập</button>'}));`],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'không thể chạy trạng thái đóng NCE TypeScript');
for(const fragment of ['class="empty"','Chọn sự cố','Mở hồ sơ','<button>Lập</button>'])assert.ok(result.stdout.includes(fragment));
console.log('Action form closed HTML TypeScript tests passed');
