'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','nce','action-cancel-modal-html.ts')).href;
const program=`import {actionCancelModalHtml} from ${JSON.stringify(source)}; console.log(actionCancelModalHtml({closeButtonHtml:'<button>Đóng</button>',cancelButtonHtml:'<button>Hủy</button>'}));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'không thể chạy modal hủy NCE TypeScript');
const html=result.stdout;
for(const fragment of ['Hủy hồ sơ NCE','action-cancel-warning','id="actionCancelReason"','id="actionCancelErr"','tối thiểu 5 ký tự','<button>Đóng</button>','<button>Hủy</button>'])assert.ok(html.includes(fragment));
console.log('Action cancel modal HTML TypeScript tests passed');
