'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','audit','activity-audit-row-html.ts')).href;
const program=`import {activityAuditRowHtml} from ${JSON.stringify(source)}; console.log(JSON.stringify([activityAuditRowHtml({sequenceHtml:'#1',timeHtml:'10:00',userHtml:'An',roleHtml:'Admin',usernameHtml:' · @an',typeHtml:'Lưu',targetHtml:'QC',detailHtml:'OK'}),activityAuditRowHtml({sequenceHtml:'',timeHtml:'',userHtml:'',roleHtml:'',usernameHtml:'',typeHtml:'',targetHtml:'',detailHtml:''})]));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'không thể chạy dòng nhật ký TypeScript');
const [row,empty]=JSON.parse(result.stdout);
for(const fragment of ['audit-seq">#1','audit-time">10:00','<b>An</b>','Admin · @an','pill">Lưu','audit-detail">OK'])assert.ok(row.includes(fragment));
assert.equal((empty.match(/class="hint">—<\/span>/g)||[]).length,2);
console.log('Activity audit row HTML TypeScript tests passed');
