'use strict';
const assert = require('node:assert/strict');
const { spawnSync } = require('node:child_process');
const path = require('node:path');
const { pathToFileURL } = require('node:url');
const source = pathToFileURL(path.join(__dirname, '..', 'src', 'presentation', 'nce', 'action-cause-detail-html.ts')).href;
const program = `
  import { createActionCauseDetailHtml } from ${JSON.stringify(source)};
  const render = createActionCauseDetailHtml({ escape: value => String(value).replaceAll('<', '&lt;') });
  console.log(JSON.stringify([render({ cause: 'Thuốc thử <hết hạn>', action: 'Thay lô', completedDate: '12/08/2026', release: { status: 'Cho phép hoạt động', details: '12/08/2026 · BS A · Đã kiểm tra' } }), render({})]));
`;
const result = spawnSync(process.execPath, ['--no-warnings', '--input-type=module', '--eval', program], { cwd: path.join(__dirname, '..'), encoding: 'utf8' });
assert.equal(result.status, 0, result.stderr || 'không thể chạy action cause detail HTML TypeScript');
const [full, empty] = JSON.parse(result.stdout);
assert.match(full, /Thuốc thử &lt;hết hạn>/);
assert.match(full, /Hoàn thành hành động: 12\/08\/2026/);
assert.match(full, /Cho phép hoạt động/);
assert.match(empty, /Chưa xác định nguyên nhân/);
assert.match(empty, /Chưa ghi hành động khắc phục/);
console.log('Action cause detail HTML TypeScript tests passed');
