'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','audit','activity-audit-archive-modal-html.ts')).href;
const program=`import {activityAuditArchiveModalHtml} from ${JSON.stringify(source)}; console.log(activityAuditArchiveModalHtml({total:123,cancelButtonHtml:'<button>Hủy</button>',archiveButtonHtml:'<button>Lưu trữ</button>'}));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'không thể chạy modal lưu trữ nhật ký TypeScript');
const html=result.stdout;
for(const fragment of ['Lưu trữ nhật ký cũ','<b>123</b>','PrevHash/Hash','id="auditArchiveMonths"','value="24" selected','<button>Hủy</button>','<button>Lưu trữ</button>'])assert.ok(html.includes(fragment));
console.log('Activity audit archive modal HTML TypeScript tests passed');
