'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','nce','action-suggest-box-html.ts')).href;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--eval',`import {actionSuggestBoxHtml} from ${JSON.stringify(source)}; console.log(actionSuggestBoxHtml('Gợi ý','<div>chip</div>'));`],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'không thể chạy khung gợi ý NCE TypeScript');
assert.match(result.stdout,/<details class="action-suggestions">/);
assert.match(result.stdout,/<summary>\+ Gợi ý<\/summary>/);
assert.match(result.stdout,/<div>chip<\/div>/);
console.log('Action suggest box HTML TypeScript tests passed');
