'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','nce','action-incident-banner-html.ts')).href;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--eval',`import {actionIncidentBannerHtml} from ${JSON.stringify(source)}; console.log(actionIncidentBannerHtml({titleHtml:'Đang lập',detailsHtml:'Glucose · 12/08'}));`],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'không thể chạy dải sự cố NCE TypeScript');
for(const fragment of ['action-incident-banner','Đang lập','Glucose · 12/08'])assert.ok(result.stdout.includes(fragment));
console.log('Action incident banner HTML TypeScript tests passed');
