'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','nce','action-level-context.ts')).href;
const program=`import {actionLevelContext} from ${JSON.stringify(source)}; const tests=[{id:'x'}],cfg=(t,l)=>({l}),label=x=>'Nhãn '+x.l; console.log(JSON.stringify([actionLevelContext('x',2,'L01',tests,cfg,label),actionLevelContext('x',2,'',tests,cfg,label),actionLevelContext('z','', '',tests,cfg,label)]));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'không thể chạy ngữ cảnh mức NCE TypeScript');
assert.deepEqual(JSON.parse(result.stdout),['Mức 2 · Lô L01 (đã ghi nhận)','Nhãn 2','Mức ? · Chưa có lô']);
console.log('Action level context TypeScript tests passed');
