'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','nce','action-review-note-modal-html.ts')).href;
const program=`import {actionReviewNoteModalHtml} from ${JSON.stringify(source)}; console.log(actionReviewNoteModalHtml({title:'Duyệt hành động',label:'Ý kiến duyệt',placeholder:'Nhận xét',errorText:'Cần nhập ít nhất 3 ký tự.',closeButtonHtml:'<button>Đóng</button>',submitButtonHtml:'<button>Duyệt</button>'}));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'không thể chạy modal duyệt NCE TypeScript');
const html=result.stdout;
for(const fragment of ['Duyệt hành động','Ý kiến duyệt','placeholder="Nhận xét"','id="actionNoteInput"','id="actionNoteErr"','ít nhất 3 ký tự','<button>Đóng</button>','<button>Duyệt</button>'])assert.ok(html.includes(fragment));
console.log('Action review note modal HTML TypeScript tests passed');
