'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','nce','action-select-html.ts')).href;
const program=`import {actionSelectHtml} from ${JSON.stringify(source)}; console.log(actionSelectHtml({id:'a<id',label:'Nhãn',options:[['','—'],['ok','Đạt & đúng']],current:'old',extra:'disabled'}));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'không thể chạy select NCE TypeScript');
for(const fragment of ['id="a&lt;id"','aria-label="Nhãn"','disabled','<option value="old" selected>old</option>','Đạt &amp; đúng'])assert.ok(result.stdout.includes(fragment));
console.log('Action select HTML TypeScript tests passed');
