const assert=require('assert');
const fs=require('fs');
const path=require('path');
const root=path.join(__dirname,'..');
const source=fs.readFileSync(path.join(root,'src','presentation','nce','action-form-steps-html.ts'),'utf8');
const bridge=fs.readFileSync(path.join(root,'src','compat','modular-pilot.global.ts'),'utf8');
const form=fs.readFileSync(path.join(root,'assets','modules','action-form.js'),'utf8');

assert.match(source,/export function actionImmediateStepHtml/,'bước kiểm soát tức thời phải ở TypeScript');
assert.match(source,/export function actionRiskStepHtml/,'bước đánh giá nguy cơ phải ở TypeScript');
assert.match(source,/export function actionInvestigationStepHtml/,'bước checklist điều tra phải ở TypeScript');
assert.match(source,/export function actionCauseStepHtml/,'cụm nguyên nhân và khắc phục phải ở TypeScript');
assert.match(source,/export function actionPatientStepHtml/,'bước ảnh hưởng bệnh nhân phải ở TypeScript');
assert.match(source,/export function actionEffectivenessStepHtml/,'bước hiệu lực phải ở TypeScript');
assert.match(source,/aRiskScoreCard/,'renderer nguy cơ phải giữ vùng RPN có aria-live');
assert.match(bridge,/actionImmediateStepPresentation=actionImmediateStepPresentation/,'bridge phải công bố bước kiểm soát');
assert.match(bridge,/actionRiskStepPresentation=actionRiskStepPresentation/,'bridge phải công bố bước nguy cơ');
assert.match(bridge,/actionInvestigationStepPresentation=actionInvestigationStepPresentation/,'bridge phải công bố bước điều tra');
assert.match(bridge,/actionCauseStepPresentation=actionCauseStepPresentation/,'bridge phải công bố cụm khắc phục');
assert.match(bridge,/actionPatientStepPresentation=actionPatientStepPresentation/,'bridge phải công bố bước bệnh nhân');
assert.match(bridge,/actionEffectivenessStepPresentation=actionEffectivenessStepPresentation/,'bridge phải công bố bước hiệu lực');
assert.match(form,/globalThis\.actionImmediateStepPresentation\(/,'form NCE phải dùng renderer kiểm soát TypeScript');
assert.match(form,/globalThis\.actionRiskStepPresentation\(/,'form NCE phải dùng renderer nguy cơ TypeScript');
assert.match(form,/globalThis\.actionInvestigationStepPresentation\(/,'form NCE phải dùng renderer điều tra TypeScript');
assert.match(form,/globalThis\.actionCauseStepPresentation\(/,'form NCE phải dùng renderer khắc phục TypeScript');
assert.match(form,/globalThis\.actionPatientStepPresentation\(/,'form NCE phải dùng renderer bệnh nhân TypeScript');
assert.match(form,/globalThis\.actionEffectivenessStepPresentation\(/,'form NCE phải dùng renderer hiệu lực TypeScript');
