'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const source=pathToFileURL(path.join(__dirname,'..','src','application','nce','action-form-ui-state.ts')).href;
const program=`import {ActionFormUiState} from ${JSON.stringify(source)}; const s=new ActionFormUiState();s.startIssue({testId:'t'});s.captureDraft({a:'1'});s.toggleSection('risk',true);console.log(JSON.stringify([s.editId,s.seed,s.draftValues(),[...s.openSections]]));s.edit('n1');console.log(JSON.stringify([s.editId,s.seed,s.draft,s.openSections]));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'không thể chạy state form NCE TypeScript');
assert.deepEqual(result.stdout.trim().split(/\r?\n/).map(JSON.parse),[['',{testId:'t'},{a:'1'},['risk']],['n1',null,null,null]]);
console.log('Action form UI state TypeScript tests passed');
