'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','nce','action-reopen-modal-html.ts')).href;
const program=`import {actionReopenModalHtml} from ${JSON.stringify(source)}; console.log(actionReopenModalHtml({workflowLabelHtml:'Thiếu bằng chứng',closeButtonHtml:'<button>Đóng</button>',reopenButtonHtml:'<button>Mở lại</button>'}));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'không thể chạy modal mở lại NCE TypeScript');
const html=result.stdout;
for(const fragment of ['Mở lại hồ sơ đã duyệt','Thiếu bằng chứng','id="actionNoteInput"','id="actionNoteErr"','tối thiểu 5 ký tự','<button>Đóng</button>','<button>Mở lại</button>'])assert.ok(html.includes(fragment));
console.log('Action reopen modal HTML TypeScript tests passed');
