'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','nce','action-level-label.ts')).href;
const program=`import {actionLevelLabel} from ${JSON.stringify(source)}; console.log(JSON.stringify([actionLevelLabel(null,String,String),actionLevelLabel({level:2,lot:'L1',mean:10,sd:1,applied:'lab'},v=>'v'+v,v=>'s'+v),actionLevelLabel({level:1},String,String)]));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'không thể chạy nhãn mức NCE TypeScript');
assert.deepEqual(JSON.parse(result.stdout),['Mức ?','Mức 2 · Lô L1 · Mean v10 · SD s1 · PXN','Mức 1 · Chưa có lô · Mean undefined · SD undefined']);
console.log('Action level label TypeScript tests passed');
