'use strict';
const assert = require('node:assert/strict');
const { spawnSync } = require('node:child_process');
const path = require('node:path');
const { pathToFileURL } = require('node:url');
const source = pathToFileURL(path.join(__dirname, '..', 'src', 'presentation', 'nce', 'action-guide-content.ts')).href;
const program = `
  import { createActionGuideContent } from ${JSON.stringify(source)};
  const render = createActionGuideContent({ escape: value => String(value).replaceAll('<', '&lt;'), button: (label, action, variant) => '[' + label + '|' + action + '|' + variant + ']' });
  console.log(JSON.stringify(render([{ phase: '<P>', title: '<T>', text: '<X>' }, { phase: 'P2', title: 'T2', text: 'X2' }])));
`;
const result = spawnSync(process.execPath, ['--no-warnings', '--input-type=module', '--eval', program], { cwd: path.join(__dirname, '..'), encoding: 'utf8' });
assert.equal(result.status, 0, result.stderr || 'không thể chạy action guide content TypeScript');
const rendered = JSON.parse(result.stdout);
assert.match(rendered.body, /aria-label="Nội dung quy trình 8 bước"/);
assert.match(rendered.body, /action-guide-number">1/);
assert.match(rendered.body, /&lt;P>/);
assert.match(rendered.body, /action-guide-number">2/);
assert.match(rendered.footer, /Điều kiện khép vòng/);
assert.match(rendered.footer, /Đóng\|closeModal\(\)\|ghost/);
console.log('Action guide content TypeScript tests passed');
