'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','nce','action-staff-options-html.ts')).href;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--eval',`import {actionStaffOptionsHtml} from ${JSON.stringify(source)}; console.log(actionStaffOptionsHtml(['An','Bình & C']));`],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'không thể chạy danh sách nhân sự NCE TypeScript');
assert.match(result.stdout,/<option value="An"><\/option>/);
assert.match(result.stdout,/<option value="Bình &amp; C"><\/option>/);
console.log('Action staff options HTML TypeScript tests passed');
