'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','nce','action-investigation-field-html.ts')).href;
const program=`import {actionInvestigationFieldHtml} from ${JSON.stringify(source)}; console.log(actionInvestigationFieldHtml({stateClass:'is-ok',statusIdHtml:'aCheck',statusId:'aCheck',noteIdHtml:'aNote',titleHtml:'Máy',hintHtml:'Xác minh',stateLabelHtml:'Đạt',selectOptionsHtml:'<option>Đạt</option>',choices:[{valueHtml:'ok',labelHtml:'Đạt',active:true,value:'ok'}],noteValueHtml:'Đã kiểm',suggestHtml:'<small>Gợi ý</small>'}));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'không thể chạy ô điều tra NCE TypeScript');
for(const fragment of ['action-investigation-item is-ok','id="aCheck"','data-action="actionInvestigationChoose" data-args=\'["aCheck","ok"]\'','aria-pressed="true"','id="aNote"','<small>Gợi ý</small>'])assert.ok(result.stdout.includes(fragment));
console.log('Action investigation field HTML TypeScript tests passed');
