'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','nce','action-bias-context.ts')).href;
const program=`import {actionBiasContext} from ${JSON.stringify(source)}; const tests=[{id:'a'},{id:'b'}],cfg=(t,l)=>t.id+'-'+l; console.log(JSON.stringify([actionBiasContext({testId:'a',level:1},null,tests,cfg),actionBiasContext({testId:'a',level:1},{testId:'b',level:2},tests,cfg)]));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'không thể chạy ngữ cảnh Bias NCE TypeScript');
assert.deepEqual(JSON.parse(result.stdout),[{t:{id:'a'},l:'a-1'},{t:{id:'b'},l:'b-2'}]);
console.log('Action bias context TypeScript tests passed');
