'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','nce','action-form-section-html.ts')).href;
const program=`import {actionFormSectionHtml} from ${JSON.stringify(source)}; console.log(actionFormSectionHtml({keyHtml:'risk',key:'risk',open:true,badgeHtml:'2',titleHtml:'Nguy cơ',hintHtml:'Theo SOP',chipHtml:'<i>Thiếu</i>',bodyHtml:'<div>Nội dung</div>'}));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'không thể chạy bước form NCE TypeScript');
for(const fragment of ['data-action-section="risk"',' open ','data-toggle-action="actionSectionToggled" data-toggle-args=\'["risk"]\'', 'Nguy cơ','Theo SOP','<i>Thiếu</i>','<div>Nội dung</div>'])assert.ok(result.stdout.includes(fragment));
assert.ok(!result.stdout.includes('ontoggle='));
console.log('Action form section HTML TypeScript tests passed');
