'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','auth','avatar-modal-html.ts')).href;
const program=`import {avatarModalHtml} from ${JSON.stringify(source)}; console.log(avatarModalHtml({previewHtml:'<img src="data:x" alt="Ảnh đại diện">',pickButtonHtml:'<button type="button">Chọn tệp</button>',fileNameText:'Chưa chọn ảnh nào',clearButtonHtml:'<button>Xóa ảnh</button>',closeButtonHtml:'<button>Đóng</button>'}));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'không thể chạy avatar modal HTML TypeScript');
const html=result.stdout;
assert.match(html,/Ảnh đại diện/);
assert.match(html,/id="avatarPick"/);
assert.match(html,/style="display:none"/);
assert.match(html,/data-action="pickAvatar"/);
assert.match(html,/data-action="closeModal"/);
assert.match(html,/Chưa chọn ảnh nào/);
assert.match(html,/Xóa ảnh/);
console.log('Avatar modal HTML TypeScript tests passed');
