'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','manage','config-panel-modal-html.ts')).href;
const input={title:'Sửa Panel QC',name:'Hóa sinh',instrumentsHtml:'<option>AU5800</option>',testRowsHtml:'<label>Glucose</label>',note:'Ghi chú',active:true,cancelButtonHtml:'<button>Hủy</button>',saveButtonHtml:'<button>Lưu</button>'};
const program=`import {configPanelModalHtml} from ${JSON.stringify(source)}; console.log(configPanelModalHtml(${JSON.stringify(input)}));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'không thể chạy modal Panel QC TypeScript');
assert.match(result.stdout,/id="cfgPanelName" value="Hóa sinh"/);
assert.match(result.stdout,/id="cfgPanelInstrument"/);
assert.match(result.stdout,/<label>Glucose<\/label>/);
assert.match(result.stdout,/<button>Hủy<\/button><button>Lưu<\/button>/);
console.log('Config panel modal HTML TypeScript tests passed');
