'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','manage','config-assay-modal-html.ts')).href;
const input={title:'Sửa xét nghiệm',name:'Glucose',teaOptionsHtml:'<option value="Glucose"></option>',teaRefKey:'glucose',teaSource:'clia',unit:'mmol/L',instrumentsHtml:'<option>AU5800</option>',section:'Hóa sinh',method:'Hexokinase',decimalOptionsHtml:'<option selected>2</option>',reagent:'Beckman',tea:'10',ruleRowsHtml:'<div>1-2s</div>',hasRuleOverrides:true,cusumOn:true,cusumK:'0.5',cusumH:'4',closed:true,cancelButtonHtml:'<button>Hủy</button>',saveButtonHtml:'<button>Lưu</button>'};
const program=`import {configAssayModalHtml} from ${JSON.stringify(source)}; console.log(configAssayModalHtml(${JSON.stringify(input)}));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'không thể chạy modal Xét nghiệm TypeScript');
const html=result.stdout;
assert.match(html,/<h3>Sửa xét nghiệm<\/h3>/);assert.match(html,/id="cfgAssayName"[^>]*value="Glucose"/);assert.match(html,/id="cfgAssayInstrument"/);assert.match(html,/<div>1-2s<\/div>/);assert.match(html,/id="cfgAssayCusumOn" type="checkbox" checked/);assert.match(html,/id="cfgAssayClosed" type="checkbox" checked/);
console.log('Config-assay modal HTML TypeScript tests passed');
