'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','manage','config-instrument-modal-html.ts')).href;
const input={title:'Sửa máy xét nghiệm',name:'AU5800-01',section:'Hóa sinh',manufacturer:'Beckman Coulter',serial:'SN-01',active:true,cancelButtonHtml:'<button>Hủy</button>',saveButtonHtml:'<button>Lưu</button>'};
const program=`import {configInstrumentModalHtml} from ${JSON.stringify(source)}; console.log(configInstrumentModalHtml(${JSON.stringify(input)}));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'không thể chạy modal Máy xét nghiệm TypeScript');
const html=result.stdout;
assert.match(html,/<h3>Sửa máy xét nghiệm<\/h3>/);
assert.match(html,/id="cfgInstName" value="AU5800-01"/);
assert.match(html,/id="cfgInstSection" value="Hóa sinh"/);
assert.match(html,/id="cfgInstMfr" value="Beckman Coulter"/);
assert.match(html,/id="cfgInstSerial" aria-label="Số sê-ri" value="SN-01"/);
assert.match(html,/id="cfgInstActive" type="checkbox" checked/);
console.log('Config-instrument modal HTML TypeScript tests passed');
