'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','manage','config-assay-rule-rows-html.ts')).href;
const input=[{id:'1-2s',action:'alert',scope:'both'},{id:'2-2s',action:'',scope:''}];
const program=`import {configAssayRuleRowsHtml} from ${JSON.stringify(source)}; console.log(configAssayRuleRowsHtml(${JSON.stringify(input)}));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'không thể chạy hàng luật xét nghiệm TypeScript');
const html=result.stdout;
assert.match(html,/data-rule="1-2s"/);assert.match(html,/value="alert" selected/);assert.match(html,/value="both" selected/);assert.match(html,/data-rule="2-2s"/);assert.match(html,/value="" selected/);
console.log('Config-assay rule rows HTML TypeScript tests passed');
