'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','manage','config-lot-modal-html.ts')).href;
const input={title:'Sửa thông tin lô QC',lotNo:'1234UE',levelOptionsHtml:'<option selected>2</option>',description:'QC hóa sinh',supplier:'Randox',openedDateHtml:'<input id="cfgLotOpened">',expiryDateHtml:'<input id="cfgLotExp">',note:'Theo dõi',cancelButtonHtml:'<button>Hủy</button>',saveButtonHtml:'<button>Lưu</button>'};
const program=`import {configLotModalHtml} from ${JSON.stringify(source)}; console.log(configLotModalHtml(${JSON.stringify(input)}));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'không thể chạy modal Lô QC TypeScript');
const html=result.stdout;
assert.match(html,/<h3>Sửa thông tin lô QC<\/h3>/);
assert.match(html,/id="cfgLotNo" value="1234UE"/);
assert.match(html,/<option selected>2<\/option>/);
assert.match(html,/id="cfgLotOpened"/);
assert.match(html,/id="cfgLotExp"/);
assert.match(html,/id="cfgLotNote" aria-label="Ghi chú">Theo dõi<\/textarea>/);
console.log('Config-lot modal HTML TypeScript tests passed');
