'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','entry','entry-page-layout-html.ts')).href;
const program=`import {entryPageLayoutHtml} from ${JSON.stringify(source)}; console.log(JSON.stringify({open:entryPageLayoutHtml({pageHeadHtml:'<header>Nhập QC</header>',treeCollapsed:false,expandButtonHtml:'<button>Mở</button>',treeHeadHtml:'<h4>Danh mục</h4>',treeHtml:'<div role="treeitem">A</div>',rightHtml:'<main>Nội dung</main>'}),closed:entryPageLayoutHtml({pageHeadHtml:'',treeCollapsed:true,expandButtonHtml:'',treeHeadHtml:'',treeHtml:'',rightHtml:''})}));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'không thể chạy Entry page layout TypeScript');
const out=JSON.parse(result.stdout);
assert.match(out.open,/class="entrygrid"/) && assert.match(out.open,/id="entryTreePanel"/) && assert.match(out.open,/role="tree" aria-label="Danh mục nội kiểm"/) && assert.match(out.open,/<main>Nội dung<\/main>/);
assert.match(out.closed,/class="entrygrid tree-collapsed"/);
console.log('Entry page layout HTML TypeScript tests passed');
