'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','entry','entry-sheet-day-row-html.ts')).href;
const program=`import {entrySheetDayRowHtml} from ${JSON.stringify(source)}; console.log(entrySheetDayRowHtml({rowClass:'today has-data',date:'2026-08-14',dayOfMonth:14,today:true,cellsHtml:'<td>10.0</td>',staffHtml:'KTV A',warningRules:'1-2s',rejectRules:'',statusHtml:'<span>A</span>',noteHtml:'Ghi chú'}));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'không thể chạy Entry sheet day row TypeScript');
assert.match(result.stdout,/class="today has-data"/) && assert.match(result.stdout,/data-date="2026-08-14"/) && assert.match(result.stdout,/<b>Hôm nay<\/b>/) && assert.match(result.stdout,/qc-staff-cell/) && assert.match(result.stdout,/<td>—<\/td>/);
console.log('Entry sheet day row HTML TypeScript tests passed');
