'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const {pathToFileURL}=require('node:url');
const path=require('node:path');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','entry','entry-void-plan.ts')).href;
const program=`import { entryVoidPlan } from ${JSON.stringify(source)};console.log(JSON.stringify([entryVoidPlan(null,{}),entryVoidPlan({},null),entryVoidPlan({},{voided:true}),entryVoidPlan({},{voided:false})]));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--experimental-strip-types','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'Không thể chạy entry void plan TypeScript');
assert.deepEqual(JSON.parse(result.stdout),[{state:'unavailable'},{state:'unavailable'},{state:'unavailable'},{state:'ready'}]);
console.log('Entry void plan TypeScript tests passed');
