'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const {pathToFileURL}=require('node:url');
const path=require('node:path');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','entry','entry-sd-zero-warning-html.ts')).href;
const program=`import { createEntrySdZeroWarningHtml } from ${JSON.stringify(source)};console.log(createEntrySdZeroWarningHtml({escape:value=>'E:'+String(value)})(['SD đang bằng 0','Lô <x>']));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--experimental-strip-types','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'Không thể chạy entry SD zero warning HTML TypeScript');
assert.equal(result.stdout.trim(),'<div class="alert rej"><b>Không thể lưu.</b> E:SD đang bằng 0 Lô <x></div>');
console.log('Entry SD zero warning HTML TypeScript tests passed');
