'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','entry','entry-range-summary-html.ts')).href;
const program=`import {entryRangeSummaryHtml} from ${JSON.stringify(source)}; console.log(JSON.stringify({eligible:entryRangeSummaryHtml({open:true,summary:'N=20',source:'PXN',mean:'10.0',sd:'1.0',eligible:true,resultCount:20,dayCount:20,proposedMean:'10.2',proposedSd:'0.9',proposedCv:'8.8',actionsHtml:'<button>Áp dụng</button>'}),pending:entryRangeSummaryHtml({open:false,summary:'Chưa có dữ liệu',source:'NSX',mean:'—',sd:'—',eligible:false,resultCount:4,dayCount:3,proposedMean:'—',proposedSd:'—',proposedCv:'—',actionsHtml:''})}));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'không thể chạy Entry range summary TypeScript');
const out=JSON.parse(result.stdout);
assert.match(out.eligible,/ open/) && assert.match(out.eligible,/Dải đề xuất: Mean=10.2 SD=0.9 CV=8.8%/) && assert.match(out.eligible,/<button>Áp dụng<\/button>/);
assert.doesNotMatch(out.pending,/ open/) && assert.match(out.pending,/hiện 4 kết quả \/ 3 ngày/);
console.log('Entry range summary HTML TypeScript tests passed');
