'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const {pathToFileURL}=require('node:url');
const path=require('node:path');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','entry','entry-qc-warning-plan.ts')).href;
const program=`import { entryQcWarningPlan } from ${JSON.stringify(source)};console.log(JSON.stringify([entryQcWarningPlan([]),entryQcWarningPlan(['Ngoài ±3SD']),entryQcWarningPlan(['SD đang bằng 0','Khác'])]));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--experimental-strip-types','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'Không thể chạy entry QC warning plan TypeScript');
assert.deepEqual(JSON.parse(result.stdout),[{state:'ready',issues:[]},{state:'confirm',issues:['Ngoài ±3SD']},{state:'blocked',issues:['SD đang bằng 0','Khác']}]);
console.log('Entry QC warning plan TypeScript tests passed');
