'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','entry','entry-point-table-card-html.ts')).href;
const program=`import {entryPointTableCardHtml} from ${JSON.stringify(source)}; console.log(entryPointTableCardHtml({parallel:true,level:2,previousLot:true,lot:'L<2',pointCount:8,bodyHtml:'<table><tbody></tbody></table>'}));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'không thể chạy Entry point table card TypeScript');
assert.match(result.stdout,/qc-parallel-card/) && assert.match(result.stdout,/role="region"/) && assert.match(result.stdout,/Mức 2 · Lô cũ L<2/) && assert.match(result.stdout,/Song song/) && assert.match(result.stdout,/8 điểm trong khoảng/) && assert.match(result.stdout,/<table>/);
console.log('Entry point table card HTML TypeScript tests passed');
