'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','entry','entry-sheet-cell-html.ts')).href;
const program=`import {entrySheetCellHtml} from ${JSON.stringify(source)}; console.log(JSON.stringify({parallel:entrySheetCellHtml({parallel:true,hasAddButton:true,runInputsHtml:'<div>run</div>',addRunButtonHtml:'<button>Thêm</button>'}),basic:entrySheetCellHtml({parallel:false,hasAddButton:false,runInputsHtml:'',addRunButtonHtml:''})}));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'không thể chạy Entry sheet cell TypeScript');
const out=JSON.parse(result.stdout);
assert.match(out.parallel,/qc-parallel-cell/) && assert.match(out.parallel,/qc-run-grid has-add-btn/) && assert.match(out.parallel,/<button>Thêm<\/button>/);
assert.doesNotMatch(out.basic,/qc-parallel-cell|has-add-btn/);
console.log('Entry sheet cell HTML TypeScript tests passed');
