'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const {pathToFileURL}=require('node:url');
const path=require('node:path');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','entry','entry-range-state.ts')).href;
const program=`import { entryRangeState } from ${JSON.stringify(source)};console.log(JSON.stringify([entryRangeState(30,{days:7,start:null,end:null}),entryRangeState(30,{start:'2026-08-01',end:'2026-08-13'}),entryRangeState(30,{start:null,end:'2026-08-13'})]));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--experimental-strip-types','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'Không thể chạy entry range state TypeScript');
assert.deepEqual(JSON.parse(result.stdout),[{days:7,start:null,end:null},{days:30,start:'2026-08-01',end:'2026-08-13'},{days:30,start:null,end:'2026-08-13'}]);
console.log('Entry range state TypeScript tests passed');
