'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','entry','entry-cumulative-stats-html.ts')).href;
const program=`import {entryCumulativeStatsHtml} from ${JSON.stringify(source)}; console.log(entryCumulativeStatsHtml({endDateText:'14/08/2026',count:20,mean:'10.25',sd:'0.52',cv:'5.1%'}));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'không thể chạy Entry cumulative stats TypeScript');
assert.match(result.stdout,/title="Tính từ đầu LOT đến 14\/08\/2026"/) && assert.match(result.stdout,/N tích lũy/) && assert.match(result.stdout,/Mean tích lũy/) && assert.match(result.stdout,/>5.1%<\/b>/);
console.log('Entry cumulative stats HTML TypeScript tests passed');
