'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','entry','entry-sheet-run-slot-html.ts')).href;
const program=`import {entrySheetEmptyRunHtml,entrySheetSavedRunHtml} from ${JSON.stringify(source)}; console.log(JSON.stringify({empty:entrySheetEmptyRunHtml({editable:true,title:'Nhập QC',ariaLabel:'Mức 1',date:'2026-08-14',runNo:2,levelIndex:0,changeAction:'entryInlineSave()'}),muted:entrySheetEmptyRunHtml({editable:false,title:'',ariaLabel:'',date:'',runNo:0,levelIndex:0,changeAction:''}),saved:entrySheetSavedRunHtml({previousLot:true,previousLotName:'L0',valueClass:'prev',title:'Chỉ đọc',valueText:'10.25',zText:'+1.2s',verdictText:'A'})}));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'không thể chạy Entry sheet run slot TypeScript');
const out=JSON.parse(result.stdout);
assert.match(out.empty,/qc-inline-input empty/) && assert.match(out.empty,/data-focus-run="2"/) && assert.match(out.empty,/onchange="entryInlineSave\(\)"/);
assert.match(out.muted,/qc-run-slot muted/) && assert.match(out.saved,/prev-lot-slot/) && assert.match(out.saved,/Lô L0/) && assert.match(out.saved,/>10.25<\/b>/);
console.log('Entry sheet run slot HTML TypeScript tests passed');
