'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const {pathToFileURL}=require('node:url');
const path=require('node:path');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','entry','entry-void-reason-error-state.ts')).href;
const program=`import { entryVoidReasonErrorState } from ${JSON.stringify(source)};console.log(JSON.stringify([entryVoidReasonErrorState(true),entryVoidReasonErrorState(false)]));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--experimental-strip-types','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'Không thể chạy entry void reason error state TypeScript');
assert.deepEqual(JSON.parse(result.stdout),[{showError:false,focusReason:false},{showError:true,focusReason:true}]);
console.log('Entry void reason error state TypeScript tests passed');
