'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const {pathToFileURL}=require('node:url');
const path=require('node:path');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','entry','entry-machine-filter-state.ts')).href;
const program=`import { entryMachineFilterState } from ${JSON.stringify(source)};console.log(JSON.stringify([entryMachineFilterState('M1'),entryMachineFilterState(''),entryMachineFilterState(null)]));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--experimental-strip-types','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'Không thể chạy entry machine filter state TypeScript');
assert.deepEqual(JSON.parse(result.stdout),[{machine:'M1'},{machine:'all'},{machine:'all'}]);
console.log('Entry machine filter state TypeScript tests passed');
