'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','entry','entry-levey-panel-html.ts')).href;
const program=`import {entryLeveyPanelHtml} from ${JSON.stringify(source)}; console.log(entryLeveyPanelHtml({startDateHtml:'<input id="start">',endDateHtml:'<input id="end">',dayButtonsHtml:'<button>30 ngày</button>',rangeText:'01/08/2026 – 14/08/2026 · 2 mức QC',stackHtml:'<div class="lj-mini">Mức 1</div>'}));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'không thể chạy Entry Levey panel TypeScript');
assert.match(result.stdout,/<h2 class="panel-title">Biểu đồ Levey-Jennings<\/h2>/) && assert.match(result.stdout,/<input id="start">/) && assert.match(result.stdout,/01\/08\/2026 – 14\/08\/2026/) && assert.match(result.stdout,/background:#c5221f/);
console.log('Entry Levey panel HTML TypeScript tests passed');
