'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const {pathToFileURL}=require('node:url');
const path=require('node:path');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','entry','entry-void-audit-detail.ts')).href;
const program=`import { entryVoidAuditDetail } from ${JSON.stringify(source)};console.log(entryVoidAuditDetail({dateText:'13/08',level:2,valueText:'5.20',reason:'Nhập sai'}));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--experimental-strip-types','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'Không thể chạy entry void audit detail TypeScript');
assert.equal(result.stdout.trim(),'Ngày 13/08, M2, giá trị 5.20 · Nhập sai');
console.log('Entry void audit detail TypeScript tests passed');
