'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','entry','entry-pre-save-warning-modal-html.ts')).href;
const program=`import {entryPreSaveWarningModalHtml} from ${JSON.stringify(source)}; console.log(entryPreSaveWarningModalHtml({issuesHtml:'<div class="alert warn">Ngoại lệ</div>',cancelButtonHtml:'<button>Hủy</button>',saveButtonHtml:'<button>Vẫn lưu</button>'}));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'không thể chạy Entry pre-save warning modal TypeScript');
assert.match(result.stdout,/Cảnh báo dữ liệu bất thường/) && assert.match(result.stdout,/Ngoại lệ/) && assert.match(result.stdout,/Bạn vẫn muốn lưu điểm QC này/) && assert.match(result.stdout,/entryRenderKeepScroll/) && assert.match(result.stdout,/<button>Vẫn lưu<\/button>/);
console.log('Entry pre-save warning modal HTML TypeScript tests passed');
