'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','entry','entry-void-modal-html.ts')).href;
const program=`import {entryVoidModalHtml} from ${JSON.stringify(source)}; console.log(entryVoidModalHtml({pointInfoHtml:'Ngày 14/08 · Mức 1',closeButtonHtml:'<button>×</button>',closeFooterButtonHtml:'<button>Đóng</button>',confirmButtonHtml:'<button>Xác nhận</button>'}));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'không thể chạy Entry void modal TypeScript');
assert.match(result.stdout,/<h3>Hủy điểm QC<\/h3>/) && assert.match(result.stdout,/id="voidKindInput"/) && assert.match(result.stdout,/id="voidOpenNce"/) && assert.match(result.stdout,/id="voidReasonInput"/) && assert.match(result.stdout,/Ngày 14\/08/) && assert.match(result.stdout,/<button>Xác nhận<\/button>/);
console.log('Entry void modal HTML TypeScript tests passed');
