'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const {pathToFileURL}=require('node:url');
const path=require('node:path');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','entry','entry-detail-state.ts')).href;
const program=`import { entryDetailState } from ${JSON.stringify(source)};
console.log(JSON.stringify([[...entryDetailState(['range'],'points',true)],[...entryDetailState(['range','points'],'points',false)],[...entryDetailState([], 'range',false)] ]));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--experimental-strip-types','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'Không thể chạy entry detail state TypeScript');
assert.deepEqual(JSON.parse(result.stdout),[['range','points'],['range'],[]]);
console.log('Entry detail state TypeScript tests passed');
