'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','entry','entry-points-panel-html.ts')).href;
const program=`import {entryPointsPanelHtml} from ${JSON.stringify(source)}; console.log(entryPointsPanelHtml({open:true,endDateText:'14/08/2026',startDateText:'01/08/2026',tableCardsHtml:'<article>Bảng</article>',voidedBoxHtml:'<aside>Đã hủy</aside>'}));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'không thể chạy Entry points panel TypeScript');
assert.match(result.stdout,/qc-points-panel" open/) && assert.match(result.stdout,/Thống kê tích lũy tính từ đầu LOT đến 14\/08\/2026/) && assert.match(result.stdout,/<article>Bảng<\/article>/) && assert.match(result.stdout,/<aside>Đã hủy<\/aside>/);
console.log('Entry points panel HTML TypeScript tests passed');
