'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const {pathToFileURL}=require('node:url');
const path=require('node:path');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','entry','entry-void-period-locked-html.ts')).href;
const program=`import { entryVoidPeriodLockedHtml } from ${JSON.stringify(source)};console.log(entryVoidPeriodLockedHtml());`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--experimental-strip-types','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'Không thể chạy entry void period locked HTML TypeScript');
assert.equal(result.stdout.trim(),'<div class="alert warn">Kỳ này đã chốt, không thể hủy điểm QC.</div>');
console.log('Entry void period locked HTML TypeScript tests passed');
