'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','entry','entry-sheet-day-detail-html.ts')).href;
const program=`import {entrySheetNoteHtml,entrySheetAddRunHtml} from ${JSON.stringify(source)}; console.log(JSON.stringify({edit:entrySheetNoteHtml({hasPoint:true,writable:true,placeholder:'Nhập ghi chú',changeAction:'saveNote()',manualNote:'Ghi chú',autoNote:''}),read:entrySheetNoteHtml({hasPoint:true,writable:false,placeholder:'',changeAction:'',manualNote:'',autoNote:'Cảnh báo'}),empty:entrySheetNoteHtml({hasPoint:false,writable:false,placeholder:'',changeAction:'',manualNote:'',autoNote:''}),add:entrySheetAddRunHtml({visible:true,action:'addRun()'}),none:entrySheetAddRunHtml({visible:false,action:''})}));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'không thể chạy Entry sheet day detail TypeScript');
const out=JSON.parse(result.stdout);
assert.match(out.edit,/qc-note-input/) && assert.match(out.edit,/onchange="saveNote\(\)"/) && assert.equal(out.read,'Cảnh báo') && assert.equal(out.empty,'—');
assert.match(out.add,/qc-add-run-btn/) && assert.match(out.add,/onclick="addRun\(\)"/) && assert.equal(out.none,'');
console.log('Entry sheet day detail HTML TypeScript tests passed');
