'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const {pathToFileURL}=require('node:url');
const path=require('node:path');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','entry','entry-tree-auto-open-state.ts')).href;
const program=`import { entryTreeAutoOpenState } from ${JSON.stringify(source)};
const first=entryTreeAutoOpenState(['m:M2'],null,'M1','G1','T1'),same=entryTreeAutoOpenState(first.keys,first.autoOpenKey,'M1','G1','T1'),changed=entryTreeAutoOpenState(same.keys,same.autoOpenKey,'M1','G2','T2');
console.log(JSON.stringify([[...first.keys],first.autoOpenKey,first.changed,[...same.keys],same.changed,[...changed.keys],changed.autoOpenKey,changed.changed]));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--experimental-strip-types','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'Không thể chạy entry tree auto open state TypeScript');
assert.deepEqual(JSON.parse(result.stdout),[['m:M2','m:M1','lg:M1|G1'],'M1|G1|T1',true,['m:M2','m:M1','lg:M1|G1'],false,['m:M2','m:M1','lg:M1|G1','lg:M1|G2'],'M1|G2|T2',true]);
console.log('Entry tree auto open state TypeScript tests passed');
