'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const {pathToFileURL}=require('node:url');
const path=require('node:path');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','entry','entry-unusual-data-issues-html.ts')).href;
const program=`import { createEntryUnusualDataIssuesHtml } from ${JSON.stringify(source)};
const render=createEntryUnusualDataIssuesHtml({escape:value=>'E:'+String(value)});console.log(render(['Ngoài giới hạn','<script>']));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--experimental-strip-types','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'Không thể chạy entry unusual data issues HTML TypeScript');
assert.equal(result.stdout.trim(),'<div class="alert warn">E:Ngoài giới hạn</div><div class="alert warn">E:<script></div>');
console.log('Entry unusual data issues HTML TypeScript tests passed');
