'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const {pathToFileURL}=require('node:url');
const path=require('node:path');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','entry','entry-void-confirm-dialog.ts')).href;
const program=`import { entryVoidConfirmDialog } from ${JSON.stringify(source)};console.log(JSON.stringify(entryVoidConfirmDialog('NCE được mở')));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--experimental-strip-types','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'Không thể chạy entry void confirm dialog TypeScript');
assert.deepEqual(JSON.parse(result.stdout),{kicker:'Thao tác không thể hoàn tác',title:'Hủy điểm QC',message:'Hủy điểm QC này khỏi tính toán Westgard/thống kê?',detail:'NCE được mở',confirmLabel:'Hủy điểm QC',cancelLabel:'Quay lại'});
console.log('Entry void confirm dialog TypeScript tests passed');
