'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const source=pathToFileURL(path.join(__dirname,'..','src','application','entry','entry-void-command.ts')).href;
const program=`import {createEntryVoidCommand} from ${JSON.stringify(source)};let cleared='';const command=createEntryVoidCommand({voidPoint:(_s,input)=>({point:{id:input.pointId},reason:'nhập sai',openNce:false,reusedAction:false}),clearDerived:id=>cleared=id});console.log(JSON.stringify(command.execute({state:{},tid:'t1',pointId:'p1'})));console.log(cleared);`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'không thể chạy Entry void command TypeScript');
const [output,cleared]=result.stdout.trim().split(/\r?\n/);
assert.deepEqual(JSON.parse(output).effects.save,{clearDerived:false,testId:'t1'});assert.equal(cleared,'t1');
console.log('Entry void command TypeScript tests passed');
