'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const {pathToFileURL}=require('node:url');
const path=require('node:path');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','entry','entry-record-error-html.ts')).href;
const program=`import { createEntryRecordErrorHtml } from ${JSON.stringify(source)};console.log(createEntryRecordErrorHtml({escape:value=>'E:'+String(value)})('Lỗi <x>'));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--experimental-strip-types','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'Không thể chạy entry record error HTML TypeScript');
assert.equal(result.stdout.trim(),'<div class="alert warn">E:Lỗi <x></div>');
console.log('Entry record error HTML TypeScript tests passed');
