'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const {pathToFileURL}=require('node:url');
const path=require('node:path');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','entry','entry-sheet-month-state.ts')).href;
const program=`import { entrySheetMonthState, entrySheetTodayState } from ${JSON.stringify(source)};console.log(JSON.stringify([entrySheetMonthState('2026-08'),entrySheetMonthState(null),entrySheetTodayState('2026-08')]));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--experimental-strip-types','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'Không thể chạy entry sheet month state TypeScript');
assert.deepEqual(JSON.parse(result.stdout),[{month:'2026-08',jumpToday:false,message:''},null,{month:'2026-08',jumpToday:true,message:''}]);
console.log('Entry sheet month state TypeScript tests passed');
