'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','entry','entry-sheet-day-summary-html.ts')).href;
const program=`import {createEntrySheetDaySummaryHtml} from ${JSON.stringify(source)}; const esc=value=>String(value).replace(/</g,'&lt;'),attr=value=>String(value).replace(/"/g,'&quot;'); const view=createEntrySheetDaySummaryHtml({escape:esc,escapeAttribute:attr}); console.log(JSON.stringify({staff:view.staff([{code:'A<',name:'KTV "A"'},{code:'B',name:'B'}]),empty:view.staff([]),ok:view.status(true,'ok'),warn:view.status(true,'warn'),rej:view.status(true,'rej'),none:view.status(false,'ok')}));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'không thể chạy Entry sheet summary TypeScript');
const out=JSON.parse(result.stdout);
assert.match(out.staff,/A&lt;/) && assert.match(out.staff,/KTV &quot;A&quot;/) && assert.match(out.staff,/qc-staff-sep/);
assert.equal(out.empty,'—') && assert.match(out.ok,/tag ok/) && assert.match(out.warn,/tag warn/) && assert.match(out.rej,/tag rej/) && assert.equal(out.none,'—');
console.log('Entry sheet day summary HTML TypeScript tests passed');
