'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','entry','entry-table-window-note-html.ts')).href;
const program=`import {entryTableWindowNoteHtml} from ${JSON.stringify(source)}; console.log(JSON.stringify({limited:entryTableWindowNoteHtml({limited:true,expanded:false,shown:50,total:70,actionButtonHtml:'<button>Hiện toàn bộ</button>'}),expanded:entryTableWindowNoteHtml({limited:false,expanded:true,shown:70,total:70,actionButtonHtml:'<button>Thu gọn</button>'}),none:entryTableWindowNoteHtml({limited:false,expanded:false,shown:0,total:70,actionButtonHtml:''})}));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'không thể chạy Entry table window note TypeScript');
const out=JSON.parse(result.stdout);
assert.match(out.limited,/50\/70 điểm gần nhất/) && assert.match(out.limited,/Hiện toàn bộ/);
assert.match(out.expanded,/toàn bộ 70 điểm/) && assert.match(out.expanded,/Thu gọn/);
assert.equal(out.none,'');
console.log('Entry table window note HTML TypeScript tests passed');
