'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const {pathToFileURL}=require('node:url');
const path=require('node:path');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','entry','entry-void-confirm-detail.ts')).href;
const program=`import { entryVoidConfirmDetail } from ${JSON.stringify(source)};console.log(JSON.stringify([entryVoidConfirmDetail(true),entryVoidConfirmDetail(false)]));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--experimental-strip-types','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'Không thể chạy entry void confirm detail TypeScript');
assert.deepEqual(JSON.parse(result.stdout),['Điểm vẫn được giữ trong nhật ký; hồ sơ NCE sẽ được lập mới hoặc dùng lại, và yêu cầu QC chạy lại.','Điểm vẫn được giữ trong nhật ký; thao tác này không tự mở hồ sơ NCE.']);
console.log('Entry void confirm detail TypeScript tests passed');
