'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const {pathToFileURL}=require('node:url');
const path=require('node:path');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','entry','entry-range-source-label.ts')).href;
const program=`import { entryRangeSourceLabel } from ${JSON.stringify(source)};console.log(JSON.stringify([entryRangeSourceLabel('lab'),entryRangeSourceLabel('manufacturer'),entryRangeSourceLabel(null)]));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--experimental-strip-types','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'Không thể chạy entry range source label TypeScript');
assert.deepEqual(JSON.parse(result.stdout),['PXN tự xây dựng','Nhà sản xuất','Nhà sản xuất']);
console.log('Entry range source label TypeScript tests passed');
