'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','entry','entry-voided-points-html.ts')).href;
const program=`import {entryVoidedPointsHtml} from ${JSON.stringify(source)}; console.log(JSON.stringify({filled:entryVoidedPointsHtml('<tr><td>14/08</td></tr>'),empty:entryVoidedPointsHtml('')}));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'không thể chạy Entry voided points TypeScript');
const out=JSON.parse(result.stdout);
assert.match(out.filled,/Điểm đã hủy trong khoảng/) && assert.match(out.filled,/class="qc-voided-table"/) && assert.match(out.filled,/<tr><td>14\/08<\/td><\/tr>/);
assert.equal(out.empty,'');
console.log('Entry voided points HTML TypeScript tests passed');
