'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','manage','history-panel-html.ts')).href;
const program=`import {historyPanelHtml} from ${JSON.stringify(source)}; console.log(historyPanelHtml({selectorHtml:'<select id="assay"></select>',tableHtml:'<table><tr><td>Lô 1101</td></tr></table>'}));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'không thể chạy panel lịch sử QC TypeScript');
assert.match(result.stdout,/target-matrix-panel/) && assert.match(result.stdout,/id="assay"/) && assert.match(result.stdout,/<td>Lô 1101<\/td>/);
console.log('History panel HTML TypeScript tests passed');
