'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','manage','lot-group-columns-html.ts')).href;
const columns=[{level:1,lots:[{id:'L1',lotNo:'1101',expiry:'31/08/2026',selected:true,depleted:false,locked:false,depletedLabel:''},{id:'L2',lotNo:'1102',expiry:'30/09/2026',selected:false,depleted:true,locked:true,depletedLabel:'đã hết QC'}]}];
const program=`import {lotGroupColumnsHtml} from ${JSON.stringify(source)}; console.log(lotGroupColumnsHtml(${JSON.stringify(columns)}));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'không thể chạy cột lô nhóm TypeScript');
assert.match(result.stdout,/Mức 1/);
assert.match(result.stdout,/value="L1" checked/);
assert.match(result.stdout,/value="L2"\s+disabled/);
assert.match(result.stdout,/title="Lô đã hết QC — không thể chọn"/);
console.log('Lot group columns HTML TypeScript tests passed');
