'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','manage','lot-group-status.ts')).href;
const program=`import {lotGroupStatus} from ${JSON.stringify(source)}; console.log(JSON.stringify([lotGroupStatus(true,'active',true),lotGroupStatus(false,'stopped',true),lotGroupStatus(false,'planned',false),lotGroupStatus(false,'active',true),lotGroupStatus(false,'active',false)]));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'không thể chạy trạng thái Nhóm lô TypeScript');
assert.deepEqual(JSON.parse(result.stdout),[{cls:'rej',text:'Đã lưu trữ'},{cls:'rej',text:'Đã dừng'},{cls:'warn',text:'Dự kiến'},{cls:'ok',text:'Đang hoạt động'},{cls:'none',text:'Chưa dùng'}]);
console.log('Lot-group status TypeScript tests passed');
