'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {spawnSync}=require('node:child_process');
const {pathToFileURL}=require('node:url');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','manage','lot-group-modal-html.ts')).href;
const input={title:'Sửa nhóm lô',levelLayout:'levels-2',lotColumnsHtml:'<b>Cột lô</b>',name:'Lô A/Lô B',note:'Theo dõi',cancelButtonHtml:'<button>Hủy</button>',saveButtonHtml:'<button>Lưu</button>'};
const program=`import {lotGroupModalHtml} from ${JSON.stringify(source)}; console.log(lotGroupModalHtml(${JSON.stringify(input)}));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'không thể chạy modal Nhóm lô TypeScript');
const html=result.stdout;
assert.match(html,/rcfg-group-modal levels-2/);
assert.match(html,/<h3>Sửa nhóm lô<\/h3>/);
assert.match(html,/<b>Cột lô<\/b>/);
assert.match(html,/id="cfgGroupName" value="Lô A\/Lô B"/);
assert.match(html,/id="cfgGroupNote">Theo dõi<\/textarea>/);
assert.match(html,/<button>Hủy<\/button><button>Lưu<\/button>/);
console.log('Lot-group modal HTML tests passed');
