'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','manage','lot-group-toggle-action.ts')).href;
const program=`import {lotGroupToggleAction} from ${JSON.stringify(source)}; console.log(JSON.stringify([lotGroupToggleAction(true,'active',true),lotGroupToggleAction(false,'planned',true),lotGroupToggleAction(false,'active',true)]));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'không thể chạy hành động Nhóm lô TypeScript');
assert.deepEqual(JSON.parse(result.stdout),[null,{label:'Kích hoạt',command:'activate',variant:'teal sm'},{label:'Dừng',command:'stop',variant:'ghost sm btn-stop-tint'}]);
console.log('Lot-group toggle action TypeScript tests passed');
