'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','manage','lot-group-lot-pills-html.ts')).href;
const program=`import {lotGroupLotPillsHtml} from ${JSON.stringify(source)}; console.log(lotGroupLotPillsHtml([{lotNo:'1101',level:1},{lotNo:'1102',level:2}]));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'không thể chạy pill lô nhóm TypeScript');
assert.equal(result.stdout.trim(),'<span class="pill">1101 · M1</span><span class="pill">1102 · M2</span>');
console.log('Lot-group lot pills HTML TypeScript tests passed');
