'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','manage','manage-assay-table-html.ts')).href;
const program=`import {manageAssayTableHtml} from ${JSON.stringify(source)}; console.log(JSON.stringify([manageAssayTableHtml({rowsHtml:'<tr><td>Glucose</td></tr>',emptyHtml:'<p>Trống</p>'}),manageAssayTableHtml({rowsHtml:'',emptyHtml:'<p>Trống</p>'})]));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'không thể chạy bảng xét nghiệm TypeScript');
const [table,empty]=JSON.parse(result.stdout);
assert.match(table,/assay-table/) && assert.match(table,/Tên xét nghiệm/) && assert.match(table,/<td>Glucose<\/td>/);
assert.match(empty,/panel rcfg-list/) && assert.match(empty,/<p>Trống<\/p>/) && assert.doesNotMatch(empty,/<table/);
console.log('Manage assay table HTML TypeScript tests passed');
