'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','manage','manage-instrument-table-html.ts')).href;
const program=`import {manageInstrumentTableHtml} from ${JSON.stringify(source)}; console.log(JSON.stringify([manageInstrumentTableHtml({rowsHtml:'<tr><td>AU480</td></tr>',emptyHtml:'<p>Trống</p>'}),manageInstrumentTableHtml({rowsHtml:'',emptyHtml:'<p>Trống</p>'})]));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'không thể chạy bảng máy TypeScript');
const [table,empty]=JSON.parse(result.stdout);
assert.match(table,/instrument-table/) && assert.match(table,/Nhà sản xuất/) && assert.match(table,/<td>AU480<\/td>/);
assert.match(empty,/panel rcfg-list/) && assert.match(empty,/<p>Trống<\/p>/) && assert.doesNotMatch(empty,/<table/);
console.log('Manage instrument table HTML TypeScript tests passed');
