'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const {pathToFileURL}=require('node:url');
const path=require('node:path');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','manage','manage-navigation-workflow.ts')).href;
const program=`import { createManageNavigationWorkflow } from ${JSON.stringify(source)};const flow=createManageNavigationWorkflow();console.log(JSON.stringify([flow.tab('lots'),flow.tab('x'),flow.targetLevel(2),flow.targetMatrix({panel:'P',group:'G'},'P2','')]));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--experimental-strip-types','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'Không thể chạy manage navigation workflow TypeScript');
assert.deepEqual(JSON.parse(result.stdout),['lots','instruments','2',{panel:'P2',group:'G',tab:'targets'}]);
console.log('Manage navigation workflow TypeScript tests passed');
