'use strict';
const assert = require('node:assert/strict');
const { spawnSync } = require('node:child_process');
const path = require('node:path');
const { pathToFileURL } = require('node:url');
const source = pathToFileURL(path.join(__dirname, '..', 'src', 'presentation', 'manage', 'manage-instrument-row-html.ts')).href;
const program = `
  import { createManageInstrumentRowHtml } from ${JSON.stringify(source)};
  const render = createManageInstrumentRowHtml({ escape: value => String(value).replaceAll('<', '&lt;'), quote: value => String(value).replaceAll("'", "\\\\'"), button: (label, action, variant) => '[' + label + '|' + action + '|' + variant + ']' });
  console.log(JSON.stringify([render({ id: "I'1", name: 'AU <480>', section: 'Hóa sinh', manufacturer: 'Beckman', serial: 'SN1', assayCount: 3, active: true }), render({ id: 'I2', name: 'Máy 2', assayCount: 0, active: false })]));
`;
const result = spawnSync(process.execPath, ['--no-warnings', '--input-type=module', '--eval', program], { cwd: path.join(__dirname, '..'), encoding: 'utf8' });
assert.equal(result.status, 0, result.stderr || 'không thể chạy manage instrument row HTML TypeScript');
const [active, inactive] = JSON.parse(result.stdout);
assert.match(active, /AU &lt;480>/);
assert.match(active, /Sửa\|openConfigInstrument\('I\\'1'\)\|ghost sm/);
assert.match(active, /Đang hoạt động/);
assert.match(inactive, /Chưa phân khoa/);
assert.match(inactive, /Ngừng hoạt động/);
console.log('Manage instrument row HTML TypeScript tests passed');
