'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','manage','manage-lot-config-layout-html.ts')).href;
const input={lotAddButtonHtml:'<button>Thêm lô</button>',lotRowsHtml:'<tr><td>1101</td></tr>',lotEmptyHtml:'<p>Trống lô</p>',groupAddButtonHtml:'<button>Thêm nhóm</button>',groupRowsHtml:'<article>Nhóm A</article>',groupEmptyHtml:'<p>Trống nhóm</p>'};
const program=`import {manageLotConfigLayoutHtml} from ${JSON.stringify(source)}; console.log(JSON.stringify([manageLotConfigLayoutHtml(${JSON.stringify(input)}),manageLotConfigLayoutHtml({...${JSON.stringify(input)},lotRowsHtml:'',groupRowsHtml:''})]));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'không thể chạy bố cục lô TypeScript');
const [filled,empty]=JSON.parse(result.stdout);
assert.match(filled,/lot-config-grid/) && assert.match(filled,/lot-table/) && assert.match(filled,/lot-group-list/) && assert.match(filled,/Nhóm A/);
assert.match(empty,/Trống lô/) && assert.match(empty,/Trống nhóm/) && assert.doesNotMatch(empty,/<table/);
console.log('Manage lot config layout HTML TypeScript tests passed');
