'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.join(__dirname,'..');
const route=fs.readFileSync(path.join(root,'src','presentation','manage','manage-page-controller.ts'),'utf8');
const actions=fs.readFileSync(path.join(root,'src','presentation','manage','manage-tests-actions-controller.ts'),'utf8');
const bridge=fs.readFileSync(path.join(root,'src','compat','modular-pilot.global.ts'),'utf8');

assert.match(route,/deps\.pres\.teaReferenceKindPresentation\(/,'Trạng thái TEa phải dùng bridge TypeScript');
assert.match(route,/deps\.pres\.teaReferenceRowActionsPresentation\(/,'Thao tác TEa phải dùng bridge TypeScript');
assert.match(route,/deps\.pres\.teaReferenceAddModalPresentation\(/,'Modal thêm TEa phải dùng bridge TypeScript');
assert.match(route,/deps\.pres\.teaReferenceLabProfileBodyPresentation\(/,'Nội dung hồ sơ TEa phải dùng bridge TypeScript');
assert.match(bridge,/teaReferenceKindPresentation: typeof teaReferenceKind;/,'Trạng thái TEa phải là hợp đồng bridge bắt buộc');
assert.match(bridge,/teaReferenceRowActionsPresentation: typeof teaReferenceRowActions;/,'Thao tác TEa phải là hợp đồng bridge bắt buộc');
assert.match(bridge,/teaReferenceAddModalPresentation: typeof teaReferenceAddModalHtml;/,'Modal thêm TEa phải là hợp đồng bridge bắt buộc');
assert.match(bridge,/teaReferenceLabProfileBodyPresentation: typeof teaReferenceLabProfileBodyHtml;/,'Nội dung hồ sơ TEa phải là hợp đồng bridge bắt buộc');
assert.match(bridge,/manageSearchMatchPresentation: typeof manageSearchMatch;/,'Tìm kiếm cấu hình phải là hợp đồng bridge bắt buộc');
assert.match(bridge,/manageInstrumentNamePresentation: typeof manageInstrumentName;/,'Tên máy cấu hình phải là hợp đồng bridge bắt buộc');
assert.match(bridge,/manageLotStatusPresentation: ReturnType<typeof createManageLotStatus>;/,'Trạng thái lô QC phải là hợp đồng bridge bắt buộc');

assert.match(actions,/deps\.pres\.targetSwitchModalHtml\(/,'target switch modal must use the TypeScript bridge');
assert.match(bridge,/targetSwitchModalHtml: typeof targetSwitchModalHtml;/,'target switch modal must be a required bridge contract');
assert.match(actions,/deps.pres.lotTransitionChoiceHtmlPresentation\(/,'Lot-transition picker must use the TypeScript bridge');
assert.match(bridge,/lotTransitionChoiceHtmlPresentation: typeof lotTransitionChoiceHtmlPresentation;/,'Lot-transition picker must be a required bridge contract');
assert.match(actions,/deps.pres.lotTransitionModalHtml\(/,'Lot-transition modal must use the TypeScript bridge');
assert.match(bridge,/lotTransitionModalHtml: typeof lotTransitionModalHtml;/,'Lot-transition modal must be a required bridge contract');
assert.match(actions,/deps.pres.lotTransitionTargetsHtmlPresentation\(/,'Lot-transition Mean/SD table must use the TypeScript bridge');
assert.match(bridge,/lotTransitionTargetsHtmlPresentation: typeof lotTransitionTargetsHtmlPresentation;/,'Lot-transition Mean/SD table must be a required bridge contract');
assert.match(actions,/deps.pres.configAssayModalHtml\(/,'Assay modal must use the TypeScript bridge');
assert.match(bridge,/configAssayModalHtml: typeof configAssayModalHtml;/,'Assay modal must be a required bridge contract');
assert.match(actions,/deps.pres.qcHistoryDetailModalHtml\(/,'Mean/SD history modal must use the TypeScript bridge');
assert.match(bridge,/qcHistoryDetailModalHtml: typeof qcHistoryDetailModalHtml;/,'Mean/SD history modal must be a required bridge contract');
assert.match(actions,/deps.pres.configAssayRuleRowsHtml\(/,'Assay Westgard rows must use the TypeScript bridge');
assert.match(bridge,/configAssayRuleRowsHtml: typeof configAssayRuleRowsHtml;/,'Assay Westgard rows must be a required bridge contract');
assert.match(actions,/deps.pres.configAssayTeaOptionsHtml\(/,'Assay TEa suggestions must use the TypeScript bridge');
assert.match(bridge,/configAssayTeaOptionsHtml: typeof configAssayTeaOptionsHtml;/,'Assay TEa suggestions must be a required bridge contract');
assert.match(actions,/deps.pres.configAssayInstrumentOptionsHtml\(/,'Assay instrument options must use the TypeScript bridge');
assert.match(bridge,/configAssayInstrumentOptionsHtml: typeof configAssayInstrumentOptionsHtml;/,'Assay instrument options must be a required bridge contract');
assert.match(actions,/deps.pres.configAssayDecimalOptionsHtml\(/,'Assay decimal options must use the TypeScript bridge');
assert.match(bridge,/configAssayDecimalOptionsHtml: typeof configAssayDecimalOptionsHtml;/,'Assay decimal options must be a required bridge contract');
// Lô QC (Giai đoạn 3) đã chuyển sang component React thật — configLotLevelOptionsHtml()
// giờ được LotModal.tsx gọi qua kernel.manage, không còn qua deps.pres trong actions.
const lotModal=fs.readFileSync(path.join(root,'src','react','modals','LotModal.tsx'),'utf8');
assert.match(lotModal,/getKernel\(\)\.manage\.configLotLevelOptionsHtml\(/,'Lot level options must use the TypeScript bridge');
assert.match(bridge,/configLotLevelOptionsHtml: typeof configLotLevelOptionsHtml;/,'Lot level options must be a required bridge contract');
assert.match(actions,/deps.pres.qcHistoryMeanSdRowsHtml\(/,'Mean/SD history rows must use the TypeScript bridge');
assert.match(actions,/deps.pres.qcHistoryPointRowsHtml\(/,'QC history point rows must use the TypeScript bridge');
assert.match(bridge,/qcHistoryMeanSdRowsHtml: typeof qcHistoryMeanSdRowsHtml;/,'Mean/SD history rows must be a required bridge contract');
assert.match(bridge,/qcHistoryPointRowsHtml: typeof qcHistoryPointRowsHtml;/,'QC history point rows must be a required bridge contract');
assert.match(actions,/deps.pres.targetNumberTextPresentation\(/,'Mean/SD number formatting must use the TypeScript bridge');
assert.match(bridge,/targetNumberTextPresentation: ReturnType<typeof createTargetNumberText>;/,'Mean/SD number formatting must be a required bridge contract');
assert.match(actions,/deps.pres.targetConfigAssignedPresentation\(/,'Mean/SD assignment state must use the TypeScript bridge');
assert.match(actions,/deps.pres.targetRangeDraftPresentation\(/,'Mean/SD draft normalization must use the TypeScript bridge');
assert.match(bridge,/targetConfigAssignedPresentation: typeof targetConfigAssignedPresentation;/,'Mean/SD assignment state must be a required bridge contract');
assert.match(bridge,/targetRangeDraftPresentation: ReturnType<typeof createTargetRangeDraft>;/,'Mean/SD draft normalization must be a required bridge contract');
assert.match(actions,/deps.pres.parseVnDatePresentation\(/,'Vietnamese date parsing must use the TypeScript bridge');
assert.match(bridge,/parseVnDatePresentation: typeof parseVnDate;/,'Vietnamese date parsing must be a required bridge contract');
assert.match(actions,/deps.pres.targetRangeSyncPresentation\(/,'Mean/SD range synchronization must use the TypeScript bridge');
assert.match(bridge,/targetRangeSyncPresentation: ReturnType<typeof createTargetRangeSync>;/,'Mean/SD range synchronization must be a required bridge contract');
assert.match(actions,/deps.pres.targetOverwritePicksPresentation\(/,'Mean/SD overwrite detection must use the TypeScript bridge');
assert.match(bridge,/targetOverwritePicksPresentation: typeof targetOverwritePicks;/,'Mean/SD overwrite detection must be a required bridge contract');
assert.match(route,/deps\.pres\.lotGroupStatusPresentation\(/,'Lot-group status must use the TypeScript bridge');
assert.match(bridge,/lotGroupStatusPresentation: typeof lotGroupStatusPresentation;/,'Lot-group status must be a required bridge contract');
assert.match(route,/deps\.pres\.lotGroupToggleActionPresentation\(/,'Lot-group toggle action must use the TypeScript bridge');
assert.match(bridge,/lotGroupToggleActionPresentation: typeof lotGroupToggleAction;/,'Lot-group toggle action must be a required bridge contract');
assert.match(actions,/deps.pres.targetSwitchAssayNamesPresentation\(/,'Target-switch assay names must use the TypeScript bridge');
assert.match(bridge,/targetSwitchAssayNamesPresentation: typeof targetSwitchAssayNames;/,'Target-switch assay names must be a required bridge contract');
assert.match(actions,/deps.pres.targetLockedBackfillNotePresentation\(/,'Target locked-backfill note must use the TypeScript bridge');
assert.match(bridge,/targetLockedBackfillNotePresentation: typeof targetLockedBackfillNote;/,'Target locked-backfill note must be a required bridge contract');

console.log('Manage core TypeScript bridge tests passed');
