'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const source=pathToFileURL(path.join(__dirname,'..','src','application','nce','nce-lifecycle-command.ts')).href;
const program=`import {createNceLifecycleCommand} from ${JSON.stringify(source)};
const review={reviewToken:r=>'t:'+r.id,cancelReadiness:()=>({ok:true}),approvalReadiness:()=>({ok:true}),returnReadiness:()=>({ok:true}),canReopen:()=>true,cancel:(r,n,b)=>!!n&&(r.cancelledBy=b,true),approve:(r,n,b)=>!!n&&(r.approvedBy=b,true),returnForRevision:(r,n,b)=>!!n&&(r.returnedBy=b,true),reopen:(r,n)=>!!n&&(r.reopened=true)};
const escalation={canEscalate:()=>true,createFollowUp:(rows,r)=>{const next={id:'next',parent:r.id};rows.push(next);return next}};
const command=createNceLifecycleCommand({review,escalation}),actions=[{id:'a'}],user={name:'Admin'};
const stale=command.execute({kind:'approve',actions,id:'a',token:'old',note:'ok',user});
const approved=command.execute({kind:'approve',actions,id:'a',token:'t:a',note:'ok',user});
const follow=command.execute({kind:'escalate',actions,id:'a',user});
console.log(JSON.stringify({stale,approved,follow,actions}));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'không thể chạy NCE lifecycle command TypeScript');
const output=JSON.parse(result.stdout);
assert.equal(output.stale.reason,'stale');assert.equal(output.approved.ok,true);assert.equal(output.actions[0].approvedBy,'Admin');
assert.equal(output.follow.record.id,'next');assert.equal(output.actions.length,2);
console.log('NCE lifecycle command TypeScript tests passed');
