'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','manage','qc-history-detail-modal-html.ts')).href;
const input={title:'Glucose · Mức 2 · Lô A',historyRowsHtml:'<tr><td>A</td></tr>',historyEmptyHtml:'<p>trống</p>',pointCount:1,pointRowsHtml:'<tr><td>01/01</td></tr>',pointsEmptyHtml:'<p>trống điểm</p>',closeButtonHtml:'<button>Đóng</button>'};
const program=`import {qcHistoryDetailModalHtml} from ${JSON.stringify(source)}; console.log(qcHistoryDetailModalHtml(${JSON.stringify(input)}));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'không thể chạy modal Lịch sử Mean/SD TypeScript');
const html=result.stdout;
assert.match(html,/<h3>Glucose · Mức 2 · Lô A<\/h3>/);assert.match(html,/hist-meansd-table/);assert.match(html,/hist-points-table/);assert.match(html,/Điểm QC đã nhập \(1\)/);
console.log('QC-history detail modal HTML TypeScript tests passed');
