'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','manage','qc-history-detail-rows-html.ts')).href;
const program=`import {qcHistoryMeanSdRowsHtml,qcHistoryPointRowsHtml} from ${JSON.stringify(source)}; console.log(qcHistoryMeanSdRowsHtml([{lot:'A',mean:'10',sd:'1',cumulativeMean:'10.2',cumulativeSd:'0.9',cumulativeCv:'8.8%',period:'01/01',source:'PXN'}])); console.log(qcHistoryPointRowsHtml([{date:'01/01',run:'R1',value:'10',z:'+0.1s',mean:'10',sd:'1',verdict:'Đạt',verdictClass:'ok',staffCode:'NV01'}]));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'không thể chạy hàng lịch sử Mean/SD TypeScript');
assert.match(result.stdout,/<b>A<\/b>/);assert.match(result.stdout,/10\.2/);assert.match(result.stdout,/<span class="tag ok">Đạt<\/span>/);assert.match(result.stdout,/NV01/);
console.log('QC-history detail rows HTML TypeScript tests passed');
