'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','range','range-safety-gate-html.ts')).href;
const input={nceId:'NCE-01',rule:'2-2s',biasInputActionAttrs:'data-action="rangeUpdateBiasHint" data-args=\'["t1",2]\' data-action-on="input"',thresholdText:'2.5%',noTeaHint:'Chưa có TEa'};
const program=`import {rangeSafetyGateHtml} from ${JSON.stringify(source)}; console.log(rangeSafetyGateHtml(${JSON.stringify(input)}));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'không thể chạy cổng an toàn dải QC TypeScript');
const html=result.stdout;assert.match(html,/NCE-01/);assert.match(html,/2-2s/);assert.match(html,/data-action="rangeUpdateBiasHint" data-args='\["t1",2\]' data-action-on="input"/);assert.match(html,/value="2\.5%"/);assert.match(html,/Chưa có TEa/);
assert.match(html,/data-action="hideFieldError" data-args='\["rangeGateErr"\]' data-action-on="change"/);
console.log('Range safety gate HTML TypeScript tests passed');
