'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','range','range-apply-confirmation-modal-html.ts')).href;
const program=`import {rangeApplyConfirmationModalHtml} from ${JSON.stringify(source)}; console.log(rangeApplyConfirmationModalHtml({changeSummaryHtml:'X̄: 1 → 2',gateHtml:'<div>Gate</div>',cancelButtonHtml:'<button>Hủy</button>',applyButtonHtml:'<button>Áp dụng</button>'}));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'không thể chạy xác nhận áp dụng dải TypeScript');
const html=result.stdout;assert.match(html,/Áp dụng dải PXN mới/);assert.match(html,/X̄: 1 → 2/);assert.match(html,/<div>Gate<\/div>/);assert.match(html,/id="rangeReasonInput"/);
console.log('Range apply confirmation modal HTML TypeScript tests passed');
