'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','range','range-revert-confirmation-modal-html.ts')).href;
const program=`import {rangeRevertConfirmationModalHtml} from ${JSON.stringify(source)}; console.log(rangeRevertConfirmationModalHtml({cancelButtonHtml:'<button>Hủy</button>',revertButtonHtml:'<button>Hoàn</button>'}));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'không thể chạy xác nhận hoàn dải TypeScript');
const html=result.stdout;assert.match(html,/Hoàn về dải nhà sản xuất/);assert.match(html,/id="rangeReasonInput"/);assert.match(html,/tối thiểu 5 ký tự/);assert.match(html,/<button>Hủy<\/button><button>Hoàn<\/button>/);
console.log('Range revert confirmation modal HTML TypeScript tests passed');
