'use strict';
const assert = require('node:assert/strict');
const path = require('node:path');
const { pathToFileURL } = require('node:url');
const { execFileSync } = require('node:child_process');
const source = path.join(__dirname, '..', 'src', 'presentation', 'reagent', 'reagent-create-reference-rows-html.ts');
const program = `import { reagentCreateReferenceRowsHtml } from ${JSON.stringify(pathToFileURL(source).href)}; console.log(JSON.stringify({rows:reagentCreateReferenceRowsHtml([{nameHtml:'Hóa sinh',rowsHtml:'<button>Glucose</button>'}],'<div>Trống</div>'),empty:reagentCreateReferenceRowsHtml([],'<div>Trống</div>')}));`;
const output = JSON.parse(execFileSync(process.execPath, ['--experimental-strip-types', '--input-type=module', '--eval', program], { encoding: 'utf8' }));
assert.equal(output.rows, '<div class="refcat">Hóa sinh</div><button>Glucose</button>');assert.equal(output.empty, '<div>Trống</div>');
console.log('Reagent create reference rows HTML tests passed');
