'use strict';
const assert = require('node:assert/strict');
const { spawnSync } = require('node:child_process');
const path = require('node:path');
const { pathToFileURL } = require('node:url');
const source = pathToFileURL(path.join(__dirname, '..', 'src', 'presentation', 'report', 'report-action-icon.ts')).href;
const result = spawnSync(process.execPath, ['--no-warnings', '--input-type=module', '--eval', `import { reportActionIcon } from ${JSON.stringify(source)}; console.log(JSON.stringify([reportActionIcon('print'),reportActionIcon('none')]));`], { cwd: path.join(__dirname, '..'), encoding: 'utf8' });
assert.equal(result.status, 0, result.stderr || 'khong the chay icon bao cao');
const [print, missing] = JSON.parse(result.stdout);
assert.match(print, /btn-ico/); assert.match(print, /<path/); assert.doesNotMatch(missing, /<path/);
console.log('Report action-icon TypeScript tests passed');
