'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','report','report-unlock-modal-html.ts')).href;
const program=`import {reportUnlockModalHtml} from ${JSON.stringify(source)}; console.log(reportUnlockModalHtml({titleHtml:'Mở khóa kỳ 08/2026',periodLabelHtml:'08/2026',closeButtonHtml:'<button>Đóng</button>',confirmButtonHtml:'<button>Xác nhận</button>'}));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'không thể chạy modal mở khóa kỳ TypeScript');
const html=result.stdout;
for(const fragment of ['Mở khóa kỳ 08/2026','id="unlockReasonInput"','id="unlockReasonErr"','tối thiểu 5 ký tự','<button>Đóng</button>','<button>Xác nhận</button>'])assert.ok(html.includes(fragment));
console.log('Report unlock modal HTML TypeScript tests passed');
