'use strict';
const assert = require('node:assert/strict');
const { spawnSync } = require('node:child_process');
const path = require('node:path');
const { pathToFileURL } = require('node:url');
const source = pathToFileURL(path.join(__dirname, '..', 'src', 'presentation', 'report', 'report-lock-panel-html.ts')).href;
const program = `
  import { createReportLockPanelHtml } from ${JSON.stringify(source)};
  const render = createReportLockPanelHtml({ button: (label, action, variant, _title, options) => '[' + label + '|' + action + '|' + variant + '|' + Boolean(options && options.disabled) + ']' });
  const common = { year: 2026, month: 8, months: [7, 8], years: [2025, 2026], lockListHtml: '<i>locks</i>' };
  console.log(JSON.stringify([render({ ...common, isAdmin: true, already: false }), render({ ...common, isAdmin: true, already: true }), render({ ...common, isAdmin: false, already: false })]));
`;
const result = spawnSync(process.execPath, ['--no-warnings', '--input-type=module', '--eval', program], { cwd: path.join(__dirname, '..'), encoding: 'utf8' });
assert.equal(result.status, 0, result.stderr || 'không thể chạy report lock panel HTML TypeScript');
const [admin, locked, reader] = JSON.parse(result.stdout);
assert.match(admin, /<option value="8" selected>Tháng 8<\/option>/);
assert.match(admin, /Khóa kỳ này\|reportLockPeriod\(\)\|teal\|false/);
assert.match(locked, /Kỳ này đã khóa\|\|ghost\|true/);
assert.match(reader, /select aria-label="Tháng" disabled/);
assert.match(reader, /Chỉ admin mới khóa\/mở khóa/);
assert.match(reader, /<i>locks<\/i>/);
console.log('Report lock panel HTML TypeScript tests passed');
