'use strict';
const assert = require('node:assert/strict');
const { spawnSync } = require('node:child_process');
const path = require('node:path');
const { pathToFileURL } = require('node:url');
const source = pathToFileURL(path.join(__dirname, '..', 'src', 'presentation', 'report', 'report-sign-block.ts')).href;
const program = `import { reportSignBlock } from ${JSON.stringify(source)}; console.log(reportSignBlock());`;
const result = spawnSync(process.execPath, ['--no-warnings', '--input-type=module', '--eval', program], { cwd: path.join(__dirname, '..'), encoding: 'utf8' });
assert.equal(result.status, 0, result.stderr || 'không thể chạy report sign block TypeScript');
assert.match(result.stdout, /sign-grid/);
assert.match(result.stdout, /Người thực hiện/);
assert.match(result.stdout, /Phụ trách khoa/);
console.log('Report sign block TypeScript tests passed');
