'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','sigma','sigma-cohort-modal-html.ts')).href;
const program=`import {sigmaCohortModalHtml} from ${JSON.stringify(source)}; console.log(sigmaCohortModalHtml({testName:'Glucose',cutoffDate:'31/08/2026',sectionsHtml:'<tr>row</tr>',cancelButtonHtml:'<button>cancel</button>',applyButtonHtml:'<button>apply</button>'}));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'không thể chạy modal cohort Sigma TypeScript');
const html=result.stdout;
for(const fragment of ['Glucose','31/08/2026','<tr>row</tr>','<button>cancel</button>','<button>apply</button>'])assert.ok(html.includes(fragment));
assert.match(html,/data-action="sgCohortClose"/);assert.match(html,/<th>Lô QC<\/th>/);
console.log('Sigma cohort modal HTML TypeScript tests passed');
