'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','sigma','sigma-bias-summary-html.ts')).href;
const program=`import {sigmaBiasSummaryHtml} from ${JSON.stringify(source)}; console.log(JSON.stringify([sigmaBiasSummaryHtml({validCount:0,signedMeanText:'',rmsText:'',mixedSigns:false}),sigmaBiasSummaryHtml({validCount:2,signedMeanText:'-1.25',rmsText:'1.80',mixedSigns:true})]));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'không thể chạy tóm tắt Bias Sigma TypeScript');
const [empty,summary]=JSON.parse(result.stdout);
assert.match(empty,/Chưa có vòng hợp lệ/);assert.match(summary,/Số vòng hợp lệ/);assert.match(summary,/-1.25%/);assert.match(summary,/1.80%/);assert.match(summary,/Bias đổi dấu/);
console.log('Sigma Bias summary HTML TypeScript tests passed');
