'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','sigma','sigma-opspec-cell-html.ts')).href;
const program=`import {sigmaOpSpecCellHtml} from ${JSON.stringify(source)}; console.log(JSON.stringify([sigmaOpSpecCellHtml(null),sigmaOpSpecCellHtml({capable:false,rules:[],n:0}),sigmaOpSpecCellHtml({capable:true,rules:['1-3s','2-2s'],n:2,r:2,marginal:true})]));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'không thể chạy ô OPSpecs Sigma TypeScript');
const [empty,incapable,capable]=JSON.parse(result.stdout);
assert.match(empty,/muted/);assert.match(incapable,/&lt;3σ/);assert.match(capable,/1-3s \/ 2-2s/);assert.match(capable,/N=2 · R=2 điểm\/lần chạy/);assert.match(capable,/tối đa \+ cải thiện PP/);
console.log('Sigma OPSpec cell HTML TypeScript tests passed');
