'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','sigma','sigma-mu-modal-html.ts')).href;
const program=`import {sigmaMuModalHtml} from ${JSON.stringify(source)}; console.log(sigmaMuModalHtml({sourceLabel:'08/2026',rowsHtml:'<tr>row</tr>',modelNoteHtml:'note',reviewedByValue:'Lan',reviewedDateHtml:'<input id="sgMuDate">',periodRowsHtml:'<label>period</label>',selectAllButtonHtml:'<button>all</button>',clearSelectionButtonHtml:'<button>none</button>',cancelButtonHtml:'<button>cancel</button>',applyButtonHtml:'<button>apply</button>'}));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'không thể chạy modal MU Sigma TypeScript');
const html=result.stdout;
for(const fragment of ['Kỳ gốc: 08/2026','<tr>row</tr>','note','value="Lan"','<input id="sgMuDate">','<label>period</label>','<button>all</button>','<button>none</button>','<button>cancel</button>','<button>apply</button>'])assert.ok(html.includes(fragment));
assert.match(html,/sg-mu-modal/);assert.match(html,/id="sgMuBy"/);assert.match(html,/id="sgMuDate"/);
console.log('Sigma MU modal HTML TypeScript tests passed');
