'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','sigma','sigma-mu-preview-html.ts')).href;
const program=`import {sigmaMuPreviewHtml} from ${JSON.stringify(source)}; console.log(JSON.stringify([sigmaMuPreviewHtml({hasMu:false}),sigmaMuPreviewHtml({hasMu:true,ucText:'1.25',uText:'2.50',complete:false,missingHtml:'u(cal)'})]));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'không thể chạy xem trước MU TypeScript');
const [empty,preview]=JSON.parse(result.stdout);
assert.match(empty,/Chưa có CV IQC/);assert.match(preview,/u<sub>c<\/sub>/);assert.match(preview,/1.25%/);assert.match(preview,/2.50%/);assert.match(preview,/Thiếu u\(cal\)/);assert.match(preview,/preview-state warn/);
console.log('Sigma MU preview HTML TypeScript tests passed');
