'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','sigma','sigma-mu-rows-html.ts')).href;
const program=`import {sigmaMuRowsHtml} from ${JSON.stringify(source)}; console.log(sigmaMuRowsHtml([{level:2,uCalValue:'1.5',basisValue:'CoA-2',excludeBias:true}]));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'không thể chạy hàng MU Sigma TypeScript');
const html=result.stdout;
for(const fragment of ['data-level="2"','value="1.5"','value="CoA-2"','data-sg-mu-preview="2"','value="exclude" selected','sgMuUpdatePreview()'])assert.ok(html.includes(fragment));
console.log('Sigma MU rows HTML TypeScript tests passed');
