'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','sigma','sigma-no-levels-panel-html.ts')).href;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--eval',`import {sigmaNoLevelsPanelHtml} from ${JSON.stringify(source)}; console.log(sigmaNoLevelsPanelHtml({testSelectHtml:'<select>test</select>',messageHtml:'Thiếu dữ liệu'}));`],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'không thể chạy trạng thái thiếu mức Sigma TypeScript');
for(const fragment of ['<select>test</select>','alert warn flow-control','Thiếu dữ liệu'])assert.ok(result.stdout.includes(fragment));
console.log('Sigma no-levels panel HTML TypeScript tests passed');
