'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','sigma','sigma-governing-rule-block-html.ts')).href;
const program=`import {sigmaGoverningRuleBlockHtml} from ${JSON.stringify(source)}; console.log(JSON.stringify([sigmaGoverningRuleBlockHtml(null,'—'),sigmaGoverningRuleBlockHtml({capable:true,single:true,rules:['1-3s'],n:2},'6.00'),sigmaGoverningRuleBlockHtml({capable:false,rules:[],n:0},'2.50')]));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'không thể chạy khối quy tắc Sigma TypeScript');
const [empty,single,incapable]=JSON.parse(result.stdout);
assert.equal(empty,'');assert.match(single,/alert-block flow-item ok/);assert.match(single,/1-3s/);assert.match(single,/6.00σ/);assert.match(incapable,/alert-block flow-item warn/);assert.match(incapable,/&lt;3σ/);
console.log('Sigma governing rule block HTML TypeScript tests passed');
