'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','sigma','sigma-period-row-html.ts')).href;
const program=`import {sigmaPeriodRowHtml} from ${JSON.stringify(source)}; console.log(sigmaPeriodRowHtml({id:'p1',selected:true,periodLabelHtml:'Tháng 8',periodSelectHtml:'<select></select>',levelCellsHtml:'<td>level</td>',actionHtml:'<button>export</button>'}));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'không thể chạy dòng kỳ Sigma TypeScript');
for(const fragment of ['data-sg-period-id="p1"','sg-period-selected','aria-selected="true"','Chọn kỳ Tháng 8','<select></select>','<td>level</td>','<button>export</button>'])assert.ok(result.stdout.includes(fragment));
console.log('Sigma period row HTML TypeScript tests passed');
