'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','sigma','sigma-analysis-setup-html.ts')).href;
const program=`import {sigmaAnalysisSetupHtml} from ${JSON.stringify(source)}; console.log(sigmaAnalysisSetupHtml({testSelectHtml:'<select>test</select>',fieldsHtml:'<input>fields',eflmHtml:'<div>eflm</div>',hintHtml:'hint'}));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'không thể chạy thiết lập Sigma TypeScript');
for(const fragment of ['Thiết lập phân tích','<select>test</select>','<input>fields','<div>eflm</div>','hint'])assert.ok(result.stdout.includes(fragment));
console.log('Sigma analysis setup HTML TypeScript tests passed');
