'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','sigma','sigma-cohort-rows-html.ts')).href;
const program=`import {sigmaCohortRowsHtml} from ${JSON.stringify(source)}; console.log(sigmaCohortRowsHtml([{level:1,missingLotCount:0,rows:[{level:1,showLevel:true,lotHtml:'L1',startText:'01/08',endText:'31/08',count:30,cvText:'2.10%',statusHtml:'Đủ',checked:true}]},{level:2,missingLotCount:3,rows:[]}]));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'không thể chạy hàng cohort Sigma TypeScript');
const html=result.stdout;
for(const fragment of ['name="sgCohort_1"','value="L1"','checked','01/08–31/08','2.10%','Có 3 điểm IQC chưa gắn mã lô QC'])assert.ok(html.includes(fragment));
console.log('Sigma cohort rows HTML TypeScript tests passed');
