'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','sigma','sigma-status-panel-html.ts')).href;
const program=`import {sigmaStatusPanelHtml} from ${JSON.stringify(source)}; console.log(sigmaStatusPanelHtml({periodLabel:'08/2026',testName:'Glucose',teaText:'6.0',cardsHtml:'<div>cards</div>',tipsHtml:'<div>tips</div>'}));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'không thể chạy panel trạng thái Sigma TypeScript');
const html=result.stdout;
for(const fragment of ['Kỳ đang xem: <b>08/2026</b>','Glucose','TEa 6.0%','<div>cards</div>','<div>tips</div>'])assert.ok(html.includes(fragment));
assert.match(html,/class="sgcards"/);
console.log('Sigma status panel HTML TypeScript tests passed');
