'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','sigma','sigma-mu-summary-html.ts')).href;
const program=`import {sigmaMuSummaryHtml} from ${JSON.stringify(source)}; console.log(sigmaMuSummaryHtml({periodLabel:'08/2026',cellsHtml:'<tr>cell</tr>',traceHtml:'<div>trace</div>',excludedNoteHtml:'<div>excluded</div>'}));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'không thể chạy bảng MU Sigma TypeScript');
const html=result.stdout;
for(const fragment of ['Kỳ đang xem: <b>08/2026</b>','<tr>cell</tr>','<div>trace</div>','<div>excluded</div>','Giới hạn MU cho phép (MAU)','không được công bố'])assert.ok(html.includes(fragment));
assert.match(html,/class="sg-mu-summary-table"/);assert.match(html,/<th class="num">U \(k=2\) %<\/th>/);
console.log('Sigma MU summary HTML TypeScript tests passed');
