'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','sigma','sigma-bias-modal-html.ts')).href;
const program=`import {sigmaBiasModalHtml} from ${JSON.stringify(source)}; console.log(sigmaBiasModalHtml({level:2,rowsHtml:'<tr>row</tr>',periodRowsHtml:'<label>period</label>',addRoundButtonHtml:'<button>add</button>',selectAllButtonHtml:'<button>all</button>',clearSelectionButtonHtml:'<button>none</button>',cancelButtonHtml:'<button>cancel</button>',applyButtonHtml:'<button>apply</button>'}));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'không thể chạy modal Bias Sigma TypeScript');
const html=result.stdout;
assert.match(html,/Tính Bias% từ EQA\/EQC — Mức 2/);
for(const fragment of ['<tr>row</tr>','<label>period</label>','<button>add</button>','<button>all</button>','<button>none</button>','<button>cancel</button>','<button>apply</button>'])assert.ok(html.includes(fragment));
assert.match(html,/id="sgBiasSummary"/);
console.log('Sigma Bias modal HTML TypeScript tests passed');
