'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','sigma','sigma-mu-dominant-text.ts')).href;
const program=`import {sigmaMuDominantText} from ${JSON.stringify(source)}; const fmt=(n)=>String(Math.round(n)); console.log(JSON.stringify([sigmaMuDominantText({uRw:.1,uBias:.8,uCal:.1},fmt),sigmaMuDominantText({uRw:.4,uBias:.35,uCal:.25},fmt),sigmaMuDominantText({uRw:1},fmt)]));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'không thể chạy gợi ý MU trội TypeScript');
assert.deepEqual(JSON.parse(result.stdout),['u(bias) chiếm 80%','','']);
console.log('Sigma MU dominant text TypeScript tests passed');
