'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const source=pathToFileURL(path.join(__dirname,'..','src','application','storage','storage-serialize-policy.ts')).href;
const program=`import {createStorageSerializePolicy} from ${JSON.stringify(source)};
let time=0;const policy=createStorageSerializePolicy(()=>time);const small=policy.serialize({v:1},1);const first=policy.stats();const reused=policy.serialize({v:2},1);time=11;policy.serialize({blob:'x'.repeat(3*1024*1024)},2);const medium=policy.delay();time=31;policy.serialize({blob:'x'.repeat(9*1024*1024)},3);const large=policy.delay();policy.invalidate();const afterInvalidate=policy.stats();console.log(JSON.stringify({small,first,reused,medium,large,afterInvalidate}));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8',maxBuffer:32*1024*1024});
assert.equal(result.status,0,result.stderr||'không thể chạy storage serialize policy TypeScript');
const output=JSON.parse(result.stdout);
assert.equal(output.small,'{"v":1}');assert.equal(output.reused,'{"v":1}','cùng revision phải tái sử dụng snapshot đã serialize');assert.equal(output.first.count,1);assert.equal(output.medium,700);assert.equal(output.large,1200);assert.equal(output.afterInvalidate.count,3);
console.log('Storage serialize policy TypeScript tests passed');
