'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','manage','target-matrix-panel-html.ts')).href;
const program=`import {targetMatrixPanelHtml} from ${JSON.stringify(source)}; console.log(targetMatrixPanelHtml({selectorHtml:'<select id="panel"></select>',summaryHtml:'<p>Tóm tắt</p>',contentHtml:'<table><tr><td>Glucose</td></tr></table>'}));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'không thể chạy panel Mean/SD TypeScript');
assert.match(result.stdout,/target-matrix-panel/) && assert.match(result.stdout,/id="panel"/) && assert.match(result.stdout,/Tóm tắt/) && assert.match(result.stdout,/<td>Glucose<\/td>/);
console.log('Target matrix panel HTML TypeScript tests passed');
