'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','manage','target-switch-assay-names.ts')).href;
const program=`import {targetSwitchAssayNames} from ${JSON.stringify(source)}; console.log(targetSwitchAssayNames(['Glucose',null,'Sodium','Glucose','']));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'không thể chạy tổng hợp tên xét nghiệm chuyển nhóm TypeScript');
assert.equal(result.stdout.trim(),'Glucose, Sodium');
console.log('Target switch assay names TypeScript tests passed');
