'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','manage','target-overwrite-picks.ts')).href;
const program=`import {targetOverwritePicks} from ${JSON.stringify(source)}; const lot={id:'new',lotNo:'NEW',level:2}; console.log(targetOverwritePicks([{testId:'a',lot,use:true},{testId:'b',lot,use:true},{testId:'c',lot,use:false}], [{id:'a',levels:[{level:2,qcLotId:'old'}]},{id:'b',levels:[{level:2,qcLotId:'new'}]},{id:'c',levels:[{level:2,lot:'OLD'}]}]).map(x=>x.testId).join(','));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'không thể chạy phát hiện ghi đè Mean/SD TypeScript');
assert.equal(result.stdout.trim(),'a');
console.log('Target overwrite picks TypeScript tests passed');
