'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','manage','target-locked-backfill-note.ts')).href;
const program=`import {targetLockedBackfillNote} from ${JSON.stringify(source)}; console.log(JSON.stringify([targetLockedBackfillNote({count:0,periods:[]}),targetLockedBackfillNote({count:2,periods:['08/2026']}),targetLockedBackfillNote({count:2,periods:['08/2026'],emphasize:true})]));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'không thể chạy ghi chú kỳ khóa Mean/SD TypeScript');
const [empty,plain,emphasized]=JSON.parse(result.stdout);assert.equal(empty,'');assert.match(plain,/2 điểm QC thuộc kỳ đã khóa/);assert.match(emphasized,/^ <b>2 điểm QC/);
console.log('Target locked backfill note TypeScript tests passed');
