'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','manage','target-range-sync.ts')).href;
const program=`import {createTargetRangeSync} from ${JSON.stringify(source)}; const sync=createTargetRangeSync({targetFromLimits:(low,high)=>({mean:(low+high)/2,sd:(high-low)/4}),limitsFromTarget:(mean,sd)=>({low:mean-2*sd,high:mean+2*sd})}); console.log(JSON.stringify([sync('limits',{mean:0,sd:0,low:8,high:12}),sync('target',{mean:10,sd:1,low:0,high:0})]));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'không thể chạy đồng bộ giới hạn Mean/SD TypeScript');
assert.deepEqual(JSON.parse(result.stdout),[{mean:10,sd:1},{low:8,high:12}]);
console.log('Target range sync TypeScript tests passed');
