'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','manage','tea-reference-lab-profile-modal-html.ts')).href;
const program=`import {teaReferenceLabProfileModalHtml} from ${JSON.stringify(source)}; console.log(teaReferenceLabProfileModalHtml({title:'Sửa hồ sơ TEa chuẩn hóa',bodyHtml:'<div>form</div>',removeButtonHtml:'<button>Xóa</button>',cancelButtonHtml:'<button>Hủy</button>',saveButtonHtml:'<button>Lưu</button>'}));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'không thể chạy modal hồ sơ TEa TypeScript');
const html=result.stdout;
for(const fragment of ['tea-lab-profile-modal','Sửa hồ sơ TEa chuẩn hóa','<div>form</div>','<button>Xóa</button>','<button>Hủy</button>','<button>Lưu</button>'])assert.ok(html.includes(fragment));
console.log('Tea reference lab profile modal HTML TypeScript tests passed');
