'use strict';
const assert = require('node:assert/strict');
const { spawnSync } = require('node:child_process');
const path = require('node:path');
const { pathToFileURL } = require('node:url');
const source = pathToFileURL(path.join(__dirname, '..', 'src', 'presentation', 'manage', 'tea-reference-empty-state.ts')).href;
const program = `import { teaReferenceEmptyState } from ${JSON.stringify(source)}; console.log(JSON.stringify([teaReferenceEmptyState(true), teaReferenceEmptyState(false)]));`;
const result = spawnSync(process.execPath, ['--no-warnings', '--input-type=module', '--eval', program], { cwd: path.join(__dirname, '..'), encoding: 'utf8' });
assert.equal(result.status, 0, result.stderr || 'không thể chạy tea reference empty state TypeScript');
assert.deepEqual(JSON.parse(result.stdout), [{ title: 'Không tìm thấy', description: 'Thử từ khóa khác.' }, { title: 'Chưa có bảng tham chiếu', description: 'Không có xét nghiệm nào.' }]);
console.log('Tea reference empty state TypeScript tests passed');
