'use strict';
const assert = require('node:assert/strict');
const { spawnSync } = require('node:child_process');
const path = require('node:path');
const { pathToFileURL } = require('node:url');
const source = pathToFileURL(path.join(__dirname, '..', 'src', 'presentation', 'manage', 'tea-reference-naming-title.ts')).href;
const program = `import { teaReferenceNamingTitle } from ${JSON.stringify(source)}; console.log(JSON.stringify([teaReferenceNamingTitle({ standardName: 'Glucose', abbreviation: 'GLU', matrix: 'Serum' }), teaReferenceNamingTitle({})]));`;
const result = spawnSync(process.execPath, ['--no-warnings', '--input-type=module', '--eval', program], { cwd: path.join(__dirname, '..'), encoding: 'utf8' });
assert.equal(result.status, 0, result.stderr || 'không thể chạy tea reference naming title TypeScript');
assert.deepEqual(JSON.parse(result.stdout), ['Tên chuẩn: Glucose · Viết tắt: GLU · Loại mẫu: Serum', '']);
console.log('Tea reference naming title TypeScript tests passed');
