'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','manage','tea-reference-lab-profile-body-html.ts')).href;
const input={labValue:'5.5',sourceOptionsHtml:'<option value="clia">CLIA</option>',referenceValue:'42 CFR',reasonHtml:'Lý do đã được kiểm tra',effectiveDateHtml:'<input id="teaLabEffectiveDate">',nextReviewDateHtml:'<input id="teaLabNextReviewDate">',preparedValue:'Nguyễn A',approvedValue:'Trần B',approvedDateHtml:'<input id="teaLabApprovedDate">'};
const program=`import {teaReferenceLabProfileBodyHtml} from ${JSON.stringify(source)}; console.log(teaReferenceLabProfileBodyHtml(${JSON.stringify(input)}));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'không thể chạy nội dung hồ sơ TEa TypeScript');
assert.match(result.stdout,/id="teaLabValue"/) && assert.match(result.stdout,/id="teaLabSource"/) && assert.match(result.stdout,/id="teaLabReference"/) && assert.match(result.stdout,/id="teaLabReason"/) && assert.match(result.stdout,/teaLabApprovedDate/) && assert.match(result.stdout,/Nguyễn A/);
console.log('Tea reference lab profile body HTML TypeScript tests passed');
