const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');

const program=`import {createUserManagementCommand} from './src/application/auth/user-management-command.ts';
const command=createUserManagementCommand();
const added=command.add({id:'u1',username:'tech',name:'KTV',initials:'KT',role:'tech',pagePerms:['dash'],passHash:'hash'});
const withPerms=command.updatePermissions(added,{role:'supervisor',pagePerms:['entry','reports']});
const withPass=command.resetPassword(withPerms,'new-hash',false);
const disabled=command.toggle(withPass);
const enabled=command.toggle(disabled);
const withAvatar=command.setAvatar(enabled,'data:image/png;base64,abc');
const withoutAvatar=command.clearAvatar(withAvatar);
console.log(JSON.stringify({added,withPerms,withPass,disabled,enabled,withAvatar,withoutAvatar,sameRef:added===withPerms}));`;
const output=spawnSync(process.execPath,['--experimental-strip-types','--input-type=module','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(output.status,0,output.stderr);
const value=JSON.parse(output.stdout);
assert.equal(value.added.id,'u1');assert.equal(value.added.username,'tech');assert.equal(value.added.role,'tech');assert.equal(value.added.active,true);assert.equal(value.added.mustChangePassword,true);
assert.equal(value.sameRef,false,'mỗi hàm phải trả về MỘT OBJECT MỚI, không mutate/trả lại tham chiếu cũ');
assert.equal(value.withPerms.role,'supervisor');assert.deepEqual(value.withPerms.pagePerms,['entry','reports']);
assert.equal(value.added.role,'tech','object gốc không được đổi sau khi updatePermissions() chạy — bằng chứng KHÔNG mutate tại chỗ');
assert.equal(value.withPass.passHash,'new-hash');assert.equal(value.withPass.mustChangePassword,false);
assert.equal(value.disabled.active,false);assert.equal(value.enabled.active,true);
assert.equal(value.withAvatar.avatar,'data:image/png;base64,abc');assert.equal(value.withoutAvatar.avatar,'');
console.log('User management command TypeScript tests passed');
