const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');

const program=`import {createUserAvatarCommand} from './src/application/auth/user-avatar-command.ts';
import {createUserStoreUpdate} from './src/application/auth/user-store-update.ts';
let state={users:[{id:'u1',username:'lan.nt'}]},currentUser=state.users[0];
const logs=[];let saves=0;
const manage={setAvatar:(user,dataUrl)=>({...user,avatar:dataUrl}),clearAvatar:(user)=>({...user,avatar:''})};
const userStore=createUserStoreUpdate({current:()=>state,syncCurrentUser:user=>{if(currentUser&&currentUser.id===user.id)currentUser=user;}});
const command=createUserAvatarCommand({manage,userStore,log:(type,detail,target)=>logs.push({type,detail,target}),save:()=>{saves++;}});
const staleRef=currentUser;
command.setAvatar(currentUser,'data:image/png;base64,xyz');
const afterSet={currentUserAvatar:currentUser.avatar,staleRefAvatar:staleRef.avatar,stateUserAvatar:state.users[0].avatar};
command.clearAvatar(currentUser);
const afterClear={currentUserAvatar:currentUser.avatar,stateUserAvatar:state.users[0].avatar};
const missing=command.setAvatar({id:'ghost',username:'x'},'data:x');
console.log(JSON.stringify({afterSet,afterClear,missing,logs,saves}));`;
const output=spawnSync(process.execPath,['--experimental-strip-types','--input-type=module','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(output.status,0,output.stderr);
const value=JSON.parse(output.stdout);
assert.equal(value.afterSet.currentUserAvatar,'data:image/png;base64,xyz','currentUser phải được đồng bộ theo object MỚI ngay sau setAvatar()');
assert.equal(value.afterSet.stateUserAvatar,'data:image/png;base64,xyz','state.users phải phản ánh đúng object mới, không chỉ currentUser');
assert.equal(value.afterSet.staleRefAvatar,undefined,'tham chiếu user CŨ (chụp trước khi gọi setAvatar) phải KHÔNG đổi — bằng chứng setAvatar() không còn mutate tại chỗ, tránh đúng bẫy currentUser stale đã khảo sát');
assert.equal(value.afterClear.currentUserAvatar,'');assert.equal(value.afterClear.stateUserAvatar,'');
assert.equal(value.missing,undefined,'sửa avatar cho một user không còn trong state.users phải trả undefined, không ném lỗi');
assert.equal(value.saves,2);
assert.equal(value.logs.length,2);
assert.equal(value.logs[0].target,'lan.nt');
assert.equal(value.logs[1].target,'lan.nt');
console.log('User avatar command TypeScript tests passed');
