const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');

const program=`import {createUserLifecycleCommand} from './src/application/auth/user-lifecycle-command.ts';
import {createUserStoreUpdate} from './src/application/auth/user-store-update.ts';
let state={},currentUser=null,syncCalls=0,logs=[],saves=0;
const manage={add:input=>({...input,active:true,mustChangePassword:true}),updatePermissions:(user,input)=>({...user,role:input.role,pagePerms:input.pagePerms}),resetPassword:(user,hash,mustChange)=>({...user,passHash:hash,mustChangePassword:mustChange}),toggle:user=>({...user,active:!user.active})};
const userStore=createUserStoreUpdate({current:()=>state,syncCurrentUser:user=>{syncCalls++;if(currentUser&&currentUser.id===user.id)currentUser=user;}});
const command=createUserLifecycleCommand({current:()=>state,manage,userStore,hash:async value=>'hash:'+value,log:(...item)=>logs.push(item),save:()=>saves++});
const added=await command.add({id:'u1',username:'user',role:'technician',pagePerms:['dash'],password:'secret',auditDetail:'Kỹ thuật viên'});
currentUser=added;
const updated=command.updatePermissions('u1',{role:'reviewer',pagePerms:['report'],auditDetail:'Người duyệt'});
const reset=await command.resetPassword('u1','new',false);
const toggled=command.toggle('u1');
const missingUpdate=command.updatePermissions('missing',{role:'x',pagePerms:[],auditDetail:'x'});
const removed=command.remove('u1');
const missingRemove=command.remove('missing');
console.log(JSON.stringify({added,updated,reset,toggled,missingUpdate,removed,missingRemove,state,logs,saves,syncCalls,currentUserAfter:currentUser}));`;
const output=spawnSync(process.execPath,['--experimental-strip-types','--input-type=module','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(output.status,0,output.stderr);
const value=JSON.parse(output.stdout);
assert.equal(value.added.active,true);assert.equal(value.added.mustChangePassword,true);assert.equal(value.added.passHash,'hash:secret');
assert.equal(value.updated.role,'reviewer');assert.deepEqual(value.updated.pagePerms,['report']);
assert.equal(value.reset.passHash,'hash:new');assert.equal(value.reset.mustChangePassword,false);
assert.equal(value.toggled.active,false);
assert.equal(value.missingUpdate,undefined,'cập nhật một id không tồn tại phải trả undefined, không ném lỗi');
assert.equal(value.removed.username,'user');assert.equal(value.missingRemove,undefined);
assert.deepEqual(value.state,{users:[]},'sau remove(), state.users phải rỗng — mảng MỚI, không phải mảng cũ đã splice');
assert.deepEqual(value.logs.map(item=>item[0]),['Thêm người dùng','Cập nhật quyền người dùng','Đổi mật khẩu','Khóa người dùng','Xóa người dùng']);
assert.equal(value.saves,5);
assert.equal(value.syncCalls,3,'mỗi lần replaceById() (updatePermissions/resetPassword/toggle) phải gọi syncCurrentUser đúng một lần — remove() và missingUpdate không đi qua userStore nên không tính');
assert.equal(value.currentUserAfter.active,false,'currentUser phải được đồng bộ theo user MỚI NHẤT sau mỗi lần sửa hồ sơ chính mình, không được stale');
console.log('User lifecycle command TypeScript tests passed');
