'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const source=pathToFileURL(path.join(__dirname,'..','src','presentation','auth','user-permissions-modal-html.ts')).href;
const program=`import {userPermissionsModalHtml} from ${JSON.stringify(source)}; console.log(userPermissionsModalHtml({userName:'Nguyễn A',username:'nguyena',roleSelectHtml:'<select></select>',permissionChecksHtml:'<div>Dash</div>',cancelButtonHtml:'<button>Hủy</button>',saveButtonHtml:'<button>Lưu</button>'}));`;
const result=spawnSync(process.execPath,['--no-warnings','--input-type=module','--eval',program],{cwd:path.join(__dirname,'..'),encoding:'utf8'});
assert.equal(result.status,0,result.stderr||'không thể chạy popup quyền người dùng TypeScript');
const html=result.stdout;assert.match(html,/Sửa quyền người dùng/);assert.match(html,/<b>Nguyễn A<\/b> · @nguyena/);assert.match(html,/<select><\/select>/);assert.match(html,/<div>Dash<\/div>/);
console.log('User permissions modal HTML TypeScript tests passed');
