'use strict';
const assert = require('node:assert/strict');
const { spawnSync } = require('node:child_process');
const path = require('node:path');
const { pathToFileURL } = require('node:url');
const source = pathToFileURL(path.join(__dirname, '..', 'src', 'presentation', 'westgard', 'westgard-xlsx-rows.ts')).href;
const program = `
  import { createWestgardXlsxRows } from ${JSON.stringify(source)};
  const rows = createWestgardXlsxRows({ date: value => 'D:' + value, staffCode: point => point.staff || '', verdict: level => 'V:' + level, error: rules => 'E:' + rules.join('|'), number: value => Number(value).toFixed(2) });
  console.log(JSON.stringify({ rejected: rows.detail({ p: { date: '2026-08-11', runId: '2', val: 14.2, staff: 'NV1' }, f: { level: 'rej', rules: ['1-3s'], supportRules: ['1-3s', '2-2s'] }, z: 3.2 }, 7), evidence: rows.detail({ p: { date: '2026-08-12' }, f: { level: 'ok', rules: [], supportRules: ['2-2s'] }, z: -1.2 }, 8) }));
`;
const result = spawnSync(process.execPath, ['--no-warnings', '--input-type=module', '--eval', program], { cwd: path.join(__dirname, '..'), encoding: 'utf8' });
assert.equal(result.status, 0, result.stderr || 'không thể chạy mô-đun TypeScript Westgard XLSX rows');
const output = JSON.parse(result.stdout);
assert.deepEqual(output.rejected, { index: 7, date: 'D:2026-08-11', runId: '2', staffCode: 'NV1', value: 14.2, z: '+3.20s', verdict: 'V:rej', style: 'rej', ruleText: '1-3s', error: 'E:1-3s' });
assert.equal(output.evidence.verdict, 'Bằng chứng');
assert.equal(output.evidence.ruleText, 'Bằng chứng: 2-2s');
assert.equal(output.evidence.error, 'E:2-2s');
assert.equal(output.evidence.style, 'ok');
console.log('Westgard XLSX rows TypeScript tests passed');
