export type TeaAnalyteMetaService={key:(value:unknown)=>string;builtIn:(value:unknown)=>any;byId:(id:unknown)=>any;meta:(name:unknown,record?:any)=>any;display:(name:unknown,record?:any)=>string};

export function createTeaAnalyteMeta(catalogSource:any[]|(()=>any[])):TeaAnalyteMetaService{
  const key=(value:unknown)=>String(value==null?'':value).trim().toLowerCase();
  let lastCatalog:any=null,rows:any={},byId:any={};
  const registry=()=>{const catalog=typeof catalogSource==='function'?catalogSource():catalogSource;if(catalog===lastCatalog)return{rows,byId};lastCatalog=catalog;rows=Object.freeze(Object.fromEntries((catalog||[]).map((row:any)=>{const aliases=[row.name,row.abbreviation].filter(Boolean),displayName=row.abbreviation&&key(row.abbreviation)!==key(row.name)?`${row.name} (${row.abbreviation})`:row.name;return[key(row.name),Object.freeze({analyteId:row.analyteId,displayName,standardName:row.name,abbreviation:row.abbreviation||'',aliases:Object.freeze(aliases),matrix:row.matrix})];})));byId=Object.freeze(Object.fromEntries(Object.values(rows).map((row:any)=>[row.analyteId,row])));return{rows,byId};};
  const builtIn=(value:unknown)=>{const current=registry(),normalized=key(value);return current.rows[normalized]||Object.values(current.rows).find((row:any)=>row.aliases.some((alias:any)=>key(alias)===normalized))||{};};
  const meta=(name:unknown,record?:any)=>{const current=registry(),custom=record&&typeof record==='object'?record:{},base=custom.analyteId&&current.byId[custom.analyteId]||builtIn(name),aliases=[name,base.displayName,base.standardName,base.abbreviation,...(base.aliases||[]),custom.displayName,custom.standardName,custom.abbreviation,...(custom.aliases||[])].filter(Boolean);return{analyteId:custom.analyteId||base.analyteId||'',displayName:custom.displayName||base.displayName||name||'',standardName:custom.standardName||base.standardName||name||'',abbreviation:custom.abbreviation||base.abbreviation||'',aliases:[...new Set(aliases)],matrix:custom.matrix||base.matrix||''};};
  return{key,builtIn,byId:(id:unknown)=>registry().byId[id as any]||{},meta,display:(name:unknown,record?:any)=>meta(name,record).displayName||name||''};
}
