type CanvasElement=Element&{dataset:Record<string,string|undefined>};

export function createAfterRenderController(deps:{document:Document;canvas:{drawVisibleCanvas:(canvas:any,draw:()=>void)=>void;disconnectObservers:()=>void};tests:()=>any[];levelConfig:(test:any,level:number)=>any;buildLeveyJennings:(input:any)=>any;acceptedLotPoints:(test:any,level:number)=>any[];drawLeveyJennings:(canvas:any,points:any[],mean:number,sd:number)=>void;entryCache:()=>any;multiViews:(test:any)=>any[];buildMultiLevel:(input:any)=>any;drawMultiLevel:(canvas:any,chart:any,test:any)=>void;lotGroups:()=>any[];levelsForLotGroup:(group:any)=>any[];archivedMultiViews:(levels:any[])=>any[];operationalLotPoints:(test:any,level:number)=>any[];cusumSeries:(test:any,level:any)=>any;buildCusum:(input:any)=>any;drawCusum:(canvas:any,points:any[],series:any)=>void;fillDefaultDates:()=>void;runPageActions:()=>void;consumeEntryJump:()=>boolean;requestFrame:(work:()=>void)=>unknown;scrollEntryJump:()=>void;updateSaveStatus:()=>void;updateBackupBanner:()=>void;restoreConfigNavScroll:()=>void}){
  const testFor=(canvas:CanvasElement)=>deps.tests().find(test=>test.id===canvas.dataset.test);
  const canvases=(selector:string)=>Array.from(deps.document.querySelectorAll(selector)) as CanvasElement[];
  const afterRender=(page:string)=>{
    deps.canvas.disconnectObservers();
    canvases('canvas.ljc').forEach(canvas=>deps.canvas.drawVisibleCanvas(canvas,()=>{const test=testFor(canvas);if(!test)return;const level=deps.levelConfig(test,parseInt(canvas.dataset.level||'',10));if(!level)return;const chart=deps.buildLeveyJennings({points:deps.acceptedLotPoints(test,level.level),mean:level.mean,sd:level.sd});deps.drawLeveyJennings(canvas,chart.points,chart.mean,chart.sd);}));
    canvases('canvas.entryLJStack').forEach(canvas=>deps.canvas.drawVisibleCanvas(canvas,()=>{const test=testFor(canvas);if(!test)return;const level=deps.levelConfig(test,parseInt(canvas.dataset.level||'',10));if(!level)return;const lot=canvas.dataset.lot||level.lot||'',key=`${level.level}|${lot}`,cache=deps.entryCache(),cached=cache&&cache.testId===canvas.dataset.test&&cache.start===canvas.dataset.start&&cache.end===canvas.dataset.end?cache.levels.get(key):null,points=cached||deps.acceptedLotPoints(test,level.level),mean=Number.isFinite(+canvas.dataset.mean!)?+canvas.dataset.mean!:level.mean,sd=Number.isFinite(+canvas.dataset.sd!)?+canvas.dataset.sd!:level.sd,chart=deps.buildLeveyJennings({points,start:canvas.dataset.start,end:canvas.dataset.end,lot,mean,sd});deps.drawLeveyJennings(canvas,chart.points,chart.mean,chart.sd);}));
    canvases('canvas.wgLJMulti').forEach(canvas=>deps.canvas.drawVisibleCanvas(canvas,()=>{const test=testFor(canvas);if(test)deps.drawMultiLevel(canvas,deps.buildMultiLevel({views:deps.multiViews(test)}),test);}));
    canvases('canvas.wgLJMultiArchived').forEach(canvas=>deps.canvas.drawVisibleCanvas(canvas,()=>{const test=testFor(canvas),group=deps.lotGroups().find(item=>item.id===canvas.dataset.group);if(test&&group)deps.drawMultiLevel(canvas,deps.buildMultiLevel({views:deps.archivedMultiViews(deps.levelsForLotGroup(group).filter(item=>item.t.id===test.id))}),test);}));
    canvases('canvas.cusumChart').forEach(canvas=>deps.canvas.drawVisibleCanvas(canvas,()=>{const test=testFor(canvas);if(!test)return;const level=deps.levelConfig(test,parseInt(canvas.dataset.level||'',10));if(!level)return;const chart=deps.buildCusum({points:deps.operationalLotPoints(test,level.level),series:deps.cusumSeries(test,level)});deps.drawCusum(canvas,chart.points,chart.series);}));
    deps.fillDefaultDates();deps.runPageActions();
    if(page==='entry'&&deps.consumeEntryJump())deps.requestFrame(()=>deps.scrollEntryJump());
    deps.updateSaveStatus();deps.updateBackupBanner();deps.restoreConfigNavScroll();
  };
  return{afterRender};
}
