export type ConfigAssayModalInput = {
  title: string; name: string; teaOptionsHtml: string; teaRefKey: string; teaSource: string; unit: string; instrumentsHtml: string; section: string; method: string; decimalOptionsHtml: string; reagent: string; tea: string; ruleRowsHtml: string; hasRuleOverrides: boolean; cusumOn: boolean; cusumK: string; cusumH: string; closed: boolean; cancelButtonHtml: string; saveButtonHtml: string;
};

export function configAssayModalHtml(input: ConfigAssayModalInput) {
  return `<div class="modal rcfg-modal rcfg-assay-modal"><div class="modal-h"><div><h3>${input.title}</h3></div><button class="modal-close" data-action="closeModal">✕</button></div><div class="modal-b">
    <div class="assay-form-heading"><h4>Thông tin xét nghiệm</h4></div>
    <div class="assay-main-grid"><div><label>Tên xét nghiệm <span class="req">*</span></label><input id="cfgAssayName" list="cfgAssayTeaSuggestions" autocomplete="off" value="${input.name}" placeholder="Gõ tên, viết tắt hoặc bí danh" data-action="configAssaySuggestionInput" data-action-on="input"><datalist id="cfgAssayTeaSuggestions">${input.teaOptionsHtml}</datalist><input id="cfgAssayTeaRefKey" type="hidden" value="${input.teaRefKey}"><input id="cfgAssayTeaSource" type="hidden" value="${input.teaSource}"></div><div><label>Đơn vị</label><input id="cfgAssayUnit" aria-label="Đơn vị" value="${input.unit}"></div><div><label>Máy xét nghiệm <span class="req">*</span></label><select id="cfgAssayInstrument" aria-label="Máy xét nghiệm" data-action="configAssayInstrumentChanged" data-action-on="change">${input.instrumentsHtml}</select></div><div><label>Khoa / Khu vực</label><input id="cfgAssaySection" value="${input.section}" placeholder="VD: Điện giải"></div></div>
    <div class="assay-detail-grid"><div><label>Phương pháp</label><input id="cfgAssayMethod" aria-label="Phương pháp" value="${input.method}"></div><div><label>Số thập phân</label><select id="cfgAssayDecimals" aria-label="Số chữ số thập phân">${input.decimalOptionsHtml}</select></div><div><label>Hóa chất</label><input id="cfgAssayReagent" aria-label="Hóa chất" value="${input.reagent}"></div><div><label>TEa %</label><input id="cfgAssayTea" aria-label="TEa %" type="number" step="any" value="${input.tea}"></div></div>
    <details class="assay-advanced" ${input.hasRuleOverrides?'open':''}><summary><span><b>Cấu hình Westgard nâng cao</b><small>Mặc định dùng cấu hình chung của hệ thống</small></span></summary><div class="assay-advanced-body"><div class="assay-rule-head" aria-hidden="true"><span>Luật</span><span>Hành động</span><span>Phạm vi áp dụng</span></div><div class="assay-rule-grid">${input.ruleRowsHtml}</div></div></details>
    <details class="assay-advanced" ${input.cusumOn?'open':''}><summary><span><b>Giám sát xu hướng CUSUM</b><small>Tùy chọn hỗ trợ phát hiện trôi hoặc dịch chuyển kéo dài</small></span></summary><div class="assay-advanced-body"><label class="rcfg-check"><input id="cfgAssayCusumOn" type="checkbox" ${input.cusumOn?'checked':''}> Bật biểu đồ CUSUM cho xét nghiệm này</label><div class="assay-cusum-grid"><div><label>Ngưỡng tích lũy k (SD)</label><input id="cfgAssayCusumK" aria-label="Ngưỡng tích lũy k (SD)" type="number" step="0.1" min="0.1" value="${input.cusumK}"></div><div><label>Ngưỡng cảnh báo h (SD)</label><input id="cfgAssayCusumH" aria-label="Ngưỡng cảnh báo h (SD)" type="number" step="0.5" min="0.5" value="${input.cusumH}"></div></div></div></details>
    <label class="rcfg-check"><input id="cfgAssayClosed" type="checkbox" ${input.closed?'checked':''}> Ngừng sử dụng xét nghiệm này cho cấu hình QC mới</label></div>
    <div class="modal-f">${input.cancelButtonHtml}${input.saveButtonHtml}</div></div>`;
}
